input PurchaseOrderToSupplyBroadcastPayloadInput {
  broadcastedByTag: TagForNotifPayloadInput!
  purchaseOrderToSupply: PurchaseOrderToSupplyForNotifPayloadInput!
}

type PurchaseOrderToSupplyBroadcastPayload {
  broadcastedByTag: TagForNotifPayload!
  purchaseOrderToSupply: PurchaseOrderToSupplyForNotifPayload!
}
