input AccountForPartyInput {
  _id: ObjectID!
  email: String
  language: Language
  type: AccountType
  person: PersonForPartyInput
}

input AccountForPartyFilterFields {
  _id: ObjectID
  email: StringFilterField
  language: StringFilterField
  type: StringFilterField
  person: PersonForPartyFilterFields
}

type AccountForParty {
  _id: ObjectID!
  email: String
  language: Language
  type: AccountType
  person: PersonForParty
}
