input OrganizationForPartyInput {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
}

input OrganizationForPartyFilterFields {
  _id: ObjectID
  name: StringFilterField
  phoneNumber: StringFilterField
  type: StringFilterField
}

type OrganizationForParty {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
}
