input PersonForPartyInput {
  _id: ObjectID!
  firstName: String!
  lastName: String!
  phoneNumber: String
}

input PersonForPartyFilterFields {
  _id: ObjectID
  firstName: StringFilterField
  lastName: StringFilterField
  phoneNumber: StringFilterField
}

type PersonForParty {
  _id: ObjectID!
  firstName: String!
  lastName: String!
  phoneNumber: String
}
