enum OrganizationType {
  PARTNER
  CUSTOMER
  INTERNAL
}

enum OrganizationStatus {
  PROPOSED
  APPROVED
  REVISION_NEEDED
  REJECTED
}

input NewOrganization {
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  addresses: [NewAddress]!
  bankAccount: BankAccount!
  profilePhotos: [NewOrganizationDescriptivePhoto]
  taxIdentification: NewIDCard
}

input UpdateOrganization {
  _id: ID!
  name: String
  phoneNumber: String
  status: OrganizationStatus
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  unfinalizedPoint: Int
  addresses: [UpdateAddress]!
  bankAccount: BankAccount
  profilePhotos: [UpdateOrganizationDescriptivePhoto]
  taxIdentification: UpdateIDCard
}

type Organization {
  _id: ID!
  name: String!
  phoneNumber: String!
  status: OrganizationStatus!
  type: OrganizationType!
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  point: Int
  unfinalizedPoint: Int
  addresses: [Address]!
  bankAccount: BankAccountType
  profilePhotos: [DescriptivePhoto]!
  taxIdentification: IDCard
  createdAt: String!
}
