input CreateAddressRegionGroup {
  cities: [City]
}

input InternalCreateAddressRegionGroup {
  _id: ObjectID!
  cities: [City]
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreateAddressRegionGroup {
  _id: ObjectID!
  publicId: String!
  cities: [City]
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateAddressRegionGroup
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateAddressRegionGroup {
  _id: ObjectID!
  cities: [City]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdateAddressRegionGroup {
  _id: ObjectID!
  cities: [City]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdateAddressRegionGroup {
  _id: ObjectID!
  cities: [City]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: DatabaseUpdateAddressRegionGroup
  updatedAt: Time
}

input AddressRegionGroupFilterFields {
  _id: ObjectID
  publicId: StringFilterField
  cities: StringFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: AddressRegionGroupFilterFields
  recentLog: ObjectIDOnly
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type AddressRegionGroup {
  _id: ObjectID!
  publicId: String!
  cities: [City]
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: AddressRegionGroup
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
