enum City {
  KABUPATEN_ACEH_BARAT
  KABUPATEN_ACEH_BARAT_DAYA
  KABUPATEN_ACEH_BESAR
  KABUPATEN_ACEH_JAYA
  KABUPATEN_ACEH_SELATAN
  KABUPATEN_ACEH_SINGKIL
  KABUPATEN_ACEH_TAMIANG
  KABUPATEN_ACEH_TENGAH
  KABUPATEN_ACEH_TENGGARA
  KABUPATEN_ACEH_TIMUR
  KABUPATEN_ACEH_UTARA
  KABUPATEN_ADMINISTRASI_KEPULAUAN_SERIBU
  KABUPATEN_AGAM
  KABUPATEN_ALOR
  KABUPATEN_ASAHAN
  KABUPATEN_ASMAT
  KABUPATEN_BADUNG
  KABUPATEN_BALANGAN
  KABUPATEN_BANDUNG
  KABUPATEN_BANDUNG_BARAT
  KABUPATEN_BANGGAI
  KABUPATEN_BANGGAI_KEPULAUAN
  KABUPATEN_BANGKA
  KABUPATEN_BANGKA_BARAT
  KABUPATEN_BANGKA_SELATAN
  KABUPATEN_BANGKA_TENGAH
  KABUPATEN_BANGKALAN
  KABUPATEN_BANGLI
  KABUPATEN_BANJAR
  KABUPATEN_BANJARNEGARA
  KABUPATEN_BANTAENG
  KABUPATEN_BANTUL
  KABUPATEN_BANYUASIN
  KABUPATEN_BANYUMAS
  KABUPATEN_BANYUWANGI
  KABUPATEN_BARITO_KUALA
  KABUPATEN_BARITO_SELATAN
  KABUPATEN_BARITO_TIMUR
  KABUPATEN_BARITO_UTARA
  KABUPATEN_BARRU
  KABUPATEN_BATANG
  KABUPATEN_BATANGHARI
  KABUPATEN_BATUBARA
  KABUPATEN_BEKASI
  KABUPATEN_BELITUNG
  KABUPATEN_BELITUNG_TIMUR
  KABUPATEN_BELU
  KABUPATEN_BENER_MERIAH
  KABUPATEN_BENGKALIS
  KABUPATEN_BENGKAYANG
  KABUPATEN_BENGKULU_SELATAN
  KABUPATEN_BENGKULU_TENGAH
  KABUPATEN_BENGKULU_UTARA
  KABUPATEN_BERAU
  KABUPATEN_BIAK_NUMFOR
  KABUPATEN_BIMA
  KABUPATEN_BINTAN
  KABUPATEN_BIREUEN
  KABUPATEN_BLITAR
  KABUPATEN_BLORA
  KABUPATEN_BOALEMO
  KABUPATEN_BOGOR
  KABUPATEN_BOJONEGORO
  KABUPATEN_BOLAANG_MONGONDOW
  KABUPATEN_BOLAANG_MONGONDOW_SELATAN
  KABUPATEN_BOLAANG_MONGONDOW_TIMUR
  KABUPATEN_BOLAANG_MONGONDOW_UTARA
  KABUPATEN_BOMBANA
  KABUPATEN_BONDOWOSO
  KABUPATEN_BONE
  KABUPATEN_BONE_BOLANGO
  KABUPATEN_BOVEN_DIGOEL
  KABUPATEN_BOYOLALI
  KABUPATEN_BREBES
  KABUPATEN_BULELENG
  KABUPATEN_BULUKUMBA
  KABUPATEN_BULUNGAN
  KABUPATEN_BUNGO
  KABUPATEN_BUOL
  KABUPATEN_BURU
  KABUPATEN_BURU_SELATAN
  KABUPATEN_BUTON
  KABUPATEN_BUTON_UTARA
  KABUPATEN_CIAMIS
  KABUPATEN_CIANJUR
  KABUPATEN_CILACAP
  KABUPATEN_CIREBON
  KABUPATEN_DAIRI
  KABUPATEN_DEIYAI
  KABUPATEN_DELI_SERDANG
  KABUPATEN_DEMAK
  KABUPATEN_DHARMASRAYA
  KABUPATEN_DOGIYAI
  KABUPATEN_DOMPU
  KABUPATEN_DONGGALA
  KABUPATEN_EMPAT_LAWANG
  KABUPATEN_ENDE
  KABUPATEN_ENREKANG
  KABUPATEN_FAKFAK
  KABUPATEN_FLORES_TIMUR
  KABUPATEN_GARUT
  KABUPATEN_GAYO_LUES
  KABUPATEN_GIANYAR
  KABUPATEN_GORONTALO
  KABUPATEN_GORONTALO_UTARA
  KABUPATEN_GOWA
  KABUPATEN_GRESIK
  KABUPATEN_GROBOGAN
  KABUPATEN_GUNUNG_KIDUL
  KABUPATEN_GUNUNG_MAS
  KABUPATEN_HALMAHERA_BARAT
  KABUPATEN_HALMAHERA_SELATAN
  KABUPATEN_HALMAHERA_TENGAH
  KABUPATEN_HALMAHERA_TIMUR
  KABUPATEN_HALMAHERA_UTARA
  KABUPATEN_HULU_SUNGAI_SELATAN
  KABUPATEN_HULU_SUNGAI_TENGAH
  KABUPATEN_HULU_SUNGAI_UTARA
  KABUPATEN_HUMBANG_HASUNDUTAN
  KABUPATEN_INDRAGIRI_HILIR
  KABUPATEN_INDRAGIRI_HULU
  KABUPATEN_INDRAMAYU
  KABUPATEN_INTAN_JAYA
  KABUPATEN_JAYAPURA
  KABUPATEN_JAYAWIJAYA
  KABUPATEN_JEMBER
  KABUPATEN_JEMBRANA
  KABUPATEN_JENEPONTO
  KABUPATEN_JEPARA
  KABUPATEN_JOMBANG
  KABUPATEN_KAIMANA
  KABUPATEN_KAMPAR
  KABUPATEN_KAPUAS
  KABUPATEN_KAPUAS_HULU
  KABUPATEN_KARANGANYAR
  KABUPATEN_KARANGASEM
  KABUPATEN_KARAWANG
  KABUPATEN_KARIMUN
  KABUPATEN_KARO
  KABUPATEN_KATINGAN
  KABUPATEN_KAUR
  KABUPATEN_KAYONG_UTARA
  KABUPATEN_KEBUMEN
  KABUPATEN_KEDIRI
  KABUPATEN_KEEROM
  KABUPATEN_KENDAL
  KABUPATEN_KEPAHIANG
  KABUPATEN_KEPULAUAN_ANAMBAS
  KABUPATEN_KEPULAUAN_ARU
  KABUPATEN_KEPULAUAN_MENTAWAI
  KABUPATEN_KEPULAUAN_MERANTI
  KABUPATEN_KEPULAUAN_SANGIHE
  KABUPATEN_KEPULAUAN_SELAYAR
  KABUPATEN_KEPULAUAN_SIAU_TAGULANDANG_BIARO
  KABUPATEN_KEPULAUAN_SULA
  KABUPATEN_KEPULAUAN_TALAUD
  KABUPATEN_KEPULAUAN_YAPEN
  KABUPATEN_KERINCI
  KABUPATEN_KETAPANG
  KABUPATEN_KLATEN
  KABUPATEN_KLUNGKUNG
  KABUPATEN_KOLAKA
  KABUPATEN_KOLAKA_UTARA
  KABUPATEN_KONAWE
  KABUPATEN_KONAWE_SELATAN
  KABUPATEN_KONAWE_UTARA
  KABUPATEN_KOTABARU
  KABUPATEN_KOTAWARINGIN_BARAT
  KABUPATEN_KOTAWARINGIN_TIMUR
  KABUPATEN_KUANTAN_SINGINGI
  KABUPATEN_KUBU_RAYA
  KABUPATEN_KUDUS
  KABUPATEN_KULON_PROGO
  KABUPATEN_KUNINGAN
  KABUPATEN_KUPANG
  KABUPATEN_KUTAI_BARAT
  KABUPATEN_KUTAI_KARTANEGARA
  KABUPATEN_KUTAI_TIMUR
  KABUPATEN_LABUHANBATU
  KABUPATEN_LABUHANBATU_SELATAN
  KABUPATEN_LABUHANBATU_UTARA
  KABUPATEN_LAHAT
  KABUPATEN_LAMANDAU
  KABUPATEN_LAMONGAN
  KABUPATEN_LAMPUNG_BARAT
  KABUPATEN_LAMPUNG_SELATAN
  KABUPATEN_LAMPUNG_TENGAH
  KABUPATEN_LAMPUNG_TIMUR
  KABUPATEN_LAMPUNG_UTARA
  KABUPATEN_LANDAK
  KABUPATEN_LANGKAT
  KABUPATEN_LANNY_JAYA
  KABUPATEN_LEBAK
  KABUPATEN_LEBONG
  KABUPATEN_LEMBATA
  KABUPATEN_LIMA_PULUH_KOTA
  KABUPATEN_LINGGA
  KABUPATEN_LOMBOK_BARAT
  KABUPATEN_LOMBOK_TENGAH
  KABUPATEN_LOMBOK_TIMUR
  KABUPATEN_LOMBOK_UTARA
  KABUPATEN_LUMAJANG
  KABUPATEN_LUWU
  KABUPATEN_LUWU_TIMUR
  KABUPATEN_LUWU_UTARA
  KABUPATEN_MADIUN
  KABUPATEN_MAGELANG
  KABUPATEN_MAHAKAM_ULU
  KABUPATEN_MAJALENGKA
  KABUPATEN_MAJALENGKA
  KABUPATEN_MAJENE
  KABUPATEN_MALANG
  KABUPATEN_MALINAU
  KABUPATEN_MALUKU_BARAT_DAYA
  KABUPATEN_MALUKU_TENGAH
  KABUPATEN_MALUKU_TENGGARA
  KABUPATEN_MALUKU_TENGGARA_BARAT
  KABUPATEN_MAMASA
  KABUPATEN_MAMBERAMO_RAYA
  KABUPATEN_MAMBERAMO_TENGAH
  KABUPATEN_MAMUJU
  KABUPATEN_MAMUJU_UTARA
  KABUPATEN_MANDAILING_NATAL
  KABUPATEN_MANGGARAI
  KABUPATEN_MANGGARAI_BARAT
  KABUPATEN_MANGGARAI_TIMUR
  KABUPATEN_MANOKWARI
  KABUPATEN_MAPPI
  KABUPATEN_MAROS
  KABUPATEN_MAYBRAT
  KABUPATEN_MELAWI
  KABUPATEN_MEMPAWAH
  KABUPATEN_MERANGIN
  KABUPATEN_MERAUKE
  KABUPATEN_MESUJI
  KABUPATEN_MIMIKA
  KABUPATEN_MINAHASA
  KABUPATEN_MINAHASA_SELATAN
  KABUPATEN_MINAHASA_TENGGARA
  KABUPATEN_MINAHASA_UTARA
  KABUPATEN_MOJOKERTO
  KABUPATEN_MOROWALI
  KABUPATEN_MUARA_ENIM
  KABUPATEN_MUARO_JAMBI
  KABUPATEN_MUKOMUKO
  KABUPATEN_MUNA
  KABUPATEN_MURUNG_RAYA
  KABUPATEN_MUSI_BANYUASIN
  KABUPATEN_MUSI_RAWAS
  KABUPATEN_NABIRE
  KABUPATEN_NAGAN_RAYA
  KABUPATEN_NAGEKEO
  KABUPATEN_NATUNA
  KABUPATEN_NDUGA
  KABUPATEN_NGADA
  KABUPATEN_NGANJUK
  KABUPATEN_NGAWI
  KABUPATEN_NIAS
  KABUPATEN_NIAS_BARAT
  KABUPATEN_NIAS_SELATAN
  KABUPATEN_NIAS_UTARA
  KABUPATEN_NUNUKAN
  KABUPATEN_OGAN_ILIR
  KABUPATEN_OGAN_KOMERING_ILIR
  KABUPATEN_OGAN_KOMERING_ULU
  KABUPATEN_OGAN_KOMERING_ULU_SELATAN
  KABUPATEN_OGAN_KOMERING_ULU_TIMUR
  KABUPATEN_PACITAN
  KABUPATEN_PADANG_LAWAS
  KABUPATEN_PADANG_LAWAS_UTARA
  KABUPATEN_PADANG_PARIAMAN
  KABUPATEN_PAKPAK_BHARAT
  KABUPATEN_PAMEKASAN
  KABUPATEN_PANDEGLANG
  KABUPATEN_PANGKAJENE_DAN_KEPULAUAN
  KABUPATEN_PANIAI
  KABUPATEN_PARIGI_MOUTONG
  KABUPATEN_PASAMAN
  KABUPATEN_PASAMAN_BARAT
  KABUPATEN_PASER
  KABUPATEN_PASURUAN
  KABUPATEN_PATI
  KABUPATEN_PEGUNUNGAN_BINTANG
  KABUPATEN_PEKALONGAN
  KABUPATEN_PELALAWAN
  KABUPATEN_PEMALANG
  KABUPATEN_PENAJAM_PASER_UTARA
  KABUPATEN_PESAWARAN
  KABUPATEN_PESISIR_SELATAN
  KABUPATEN_PIDIE
  KABUPATEN_PIDIE_JAYA
  KABUPATEN_PINRANG
  KABUPATEN_POHUWATO
  KABUPATEN_POLEWALI_MANDAR
  KABUPATEN_PONOROGO
  KABUPATEN_POSO
  KABUPATEN_PRINGSEWU
  KABUPATEN_PROBOLINGGO
  KABUPATEN_PULANG_PISAU
  KABUPATEN_PULAU_MOROTAI
  KABUPATEN_PUNCAK
  KABUPATEN_PUNCAK_JAYA
  KABUPATEN_PURBALINGGA
  KABUPATEN_PURWAKARTA
  KABUPATEN_PURWOREJO
  KABUPATEN_RAJA_AMPAT
  KABUPATEN_REJANG_LEBONG
  KABUPATEN_REMBANG
  KABUPATEN_ROKAN_HILIR
  KABUPATEN_ROKAN_HULU
  KABUPATEN_ROTE_NDAO
  KABUPATEN_SABU_RAIJUA
  KABUPATEN_SAMBAS
  KABUPATEN_SAMOSIR
  KABUPATEN_SAMPANG
  KABUPATEN_SANGGAU
  KABUPATEN_SARMI
  KABUPATEN_SAROLANGUN
  KABUPATEN_SEKADAU
  KABUPATEN_SELUMA
  KABUPATEN_SEMARANG
  KABUPATEN_SERAM_BAGIAN_BARAT
  KABUPATEN_SERAM_BAGIAN_TIMUR
  KABUPATEN_SERANG
  KABUPATEN_SERDANG_BEDAGAI
  KABUPATEN_SERUYAN
  KABUPATEN_SIAK
  KABUPATEN_SIDENRENG_RAPPANG
  KABUPATEN_SIDOARJO
  KABUPATEN_SIGI
  KABUPATEN_SIJUNJUNG
  KABUPATEN_SIKKA
  KABUPATEN_SIMALUNGUN
  KABUPATEN_SIMEULUE
  KABUPATEN_SINJAI
  KABUPATEN_SINTANG
  KABUPATEN_SITUBONDO
  KABUPATEN_SLEMAN
  KABUPATEN_SOLOK
  KABUPATEN_SOLOK_SELATAN
  KABUPATEN_SOPPENG
  KABUPATEN_SORONG
  KABUPATEN_SORONG_SELATAN
  KABUPATEN_SRAGEN
  KABUPATEN_SUBANG
  KABUPATEN_SUKABUMI
  KABUPATEN_SUKAMARA
  KABUPATEN_SUKOHARJO
  KABUPATEN_SUMBA_BARAT
  KABUPATEN_SUMBA_BARAT_DAYA
  KABUPATEN_SUMBA_TENGAH
  KABUPATEN_SUMBA_TIMUR
  KABUPATEN_SUMBAWA
  KABUPATEN_SUMBAWA_BARAT
  KABUPATEN_SUMEDANG
  KABUPATEN_SUMENEP
  KABUPATEN_SUPIORI
  KABUPATEN_TABALONG
  KABUPATEN_TABANAN
  KABUPATEN_TAKALAR
  KABUPATEN_TAMBRAUW
  KABUPATEN_TANA_TIDUNG
  KABUPATEN_TANA_TORAJA
  KABUPATEN_TANAH_BUMBU
  KABUPATEN_TANAH_DATAR
  KABUPATEN_TANAH_LAUT
  KABUPATEN_TANGERANG
  KABUPATEN_TANGGAMUS
  KABUPATEN_TANJUNG_JABUNG_BARAT
  KABUPATEN_TANJUNG_JABUNG_TIMUR
  KABUPATEN_TAPANULI_SELATAN
  KABUPATEN_TAPANULI_TENGAH
  KABUPATEN_TAPANULI_UTARA
  KABUPATEN_TAPIN
  KABUPATEN_TASIKMALAYA
  KABUPATEN_TEBO
  KABUPATEN_TEGAL
  KABUPATEN_TELUK_BINTUNI
  KABUPATEN_TELUK_WONDAMA
  KABUPATEN_TEMANGGUNG
  KABUPATEN_TIMOR_TENGAH_SELATAN
  KABUPATEN_TIMOR_TENGAH_UTARA
  KABUPATEN_TOBA_SAMOSIR
  KABUPATEN_TOJO_UNA-UNA
  KABUPATEN_TOLI-TOLI
  KABUPATEN_TOLIKARA
  KABUPATEN_TORAJA_UTARA
  KABUPATEN_TRENGGALEK
  KABUPATEN_TUBAN
  KABUPATEN_TULANG_BAWANG
  KABUPATEN_TULANG_BAWANG_BARAT
  KABUPATEN_TULUNGAGUNG
  KABUPATEN_WAJO
  KABUPATEN_WAKATOBI
  KABUPATEN_WAROPEN
  KABUPATEN_WAY_KANAN
  KABUPATEN_WONOGIRI
  KABUPATEN_WONOSOBO
  KABUPATEN_YAHUKIMO
  KABUPATEN_YALIMO
  KOTA_ADMINISTRASI_JAKARTA_BARAT
  KOTA_ADMINISTRASI_JAKARTA_PUSAT
  KOTA_ADMINISTRASI_JAKARTA_SELATAN
  KOTA_ADMINISTRASI_JAKARTA_TIMUR
  KOTA_ADMINISTRASI_JAKARTA_UTARA
  KOTA_AMBON
  KOTA_BALIKPAPAN
  KOTA_BANDA_ACEH
  KOTA_BANDAR_LAMPUNG
  KOTA_BANDUNG
  KOTA_BANJAR
  KOTA_BANJARBARU
  KOTA_BANJARMASIN
  KOTA_BATAM
  KOTA_BATU
  KOTA_BAU-BAU
  KOTA_BEKASI
  KOTA_BENGKULU
  KOTA_BIMA
  KOTA_BINJAI
  KOTA_BITUNG
  KOTA_BLITAR
  KOTA_BOGOR
  KOTA_BONTANG
  KOTA_BUKITTINGGI
  KOTA_CILEGON
  KOTA_CIMAHI
  KOTA_CIREBON
  KOTA_DENPASAR
  KOTA_DEPOK
  KOTA_DUMAI
  KOTA_GORONTALO
  KOTA_GUNUNGSITOLI
  KOTA_JAMBI
  KOTA_JAYAPURA
  KOTA_KEDIRI
  KOTA_KENDARI
  KOTA_KOTAMOBAGU
  KOTA_KUPANG
  KOTA_LANGSA
  KOTA_LHOKSEUMAWE
  KOTA_LUBUKLINGGAU
  KOTA_MADIUN
  KOTA_MAGELANG
  KOTA_MAKASSAR
  KOTA_MALANG
  KOTA_MANADO
  KOTA_MATARAM
  KOTA_MEDAN
  KOTA_METRO
  KOTA_MOJOKERTO
  KOTA_PADANG
  KOTA_PADANGPANJANG
  KOTA_PADANGSIDEMPUAN
  KOTA_PAGAR_ALAM
  KOTA_PALANGKA_RAYA
  KOTA_PALEMBANG
  KOTA_PALOPO
  KOTA_PALU
  KOTA_PANGKAL_PINANG
  KOTA_PAREPARE
  KOTA_PARIAMAN
  KOTA_PASURUAN
  KOTA_PAYAKUMBUH
  KOTA_PEKALONGAN
  KOTA_PEKANBARU
  KOTA_PEMATANGSIANTAR
  KOTA_PONTIANAK
  KOTA_PRABUMULIH
  KOTA_PROBOLINGGO
  KOTA_SABANG
  KOTA_SALATIGA
  KOTA_SAMARINDA
  KOTA_SAWAHLUNTO
  KOTA_SEMARANG
  KOTA_SERANG
  KOTA_SIBOLGA
  KOTA_SINGKAWANG
  KOTA_SOLOK
  KOTA_SORONG
  KOTA_SUBULUSSALAM
  KOTA_SUKABUMI
  KOTA_SUNGAI_PENUH
  KOTA_SURABAYA
  KOTA_SURAKARTA
  KOTA_TANGERANG
  KOTA_TANGERANG_SELATAN
  KOTA_TANJUNG_PINANG
  KOTA_TANJUNGBALAI
  KOTA_TARAKAN
  KOTA_TASIKMALAYA
  KOTA_TEBING_TINGGI
  KOTA_TEGAL
  KOTA_TERNATE
  KOTA_TIDORE_KEPULAUAN
  KOTA_TOMOHON
  KOTA_TUAL
  KOTA_YOGYAKARTA
}
