enum City {
  BANDAACEH
  KARAWANG
  SURAKARTA
  SAMARINDA
  LANGSA
  KAWALU
  TALANG
  TARAKAN
  LHOKSEUMAWE
  KLANGENAN
  TAMAN
  BATAM
  DENPASAR
  KUNINGAN
  TEGAL
  TANJUNGPINANG
  SINGARAJA
  LEMBANG
  UNGARAN
  BANDAR
  LAMPUNG
  PANGKALPINANG
  MAJALAYA
  WARU
  AMBON
  SUNGAILIAT
  MARGAHAYU
  WELERI
  TERNATE
  TANJUNGPANDAN
  PACET
  WONOSOBO
  BIMA
  BANJARMASIN
  PADALARANG
  BALUNG
  MATARAM
  CIKUPA
  PALIMANAN
  BANGIL
  ENDE
  CILEGON
  PAMEUNGPEUK
  BANGKALAN
  KUPANG
  CIPUTAT
  PARUNG
  BANYUWANGI
  JAYAPURA
  GUNUNGPUTRI
  PLUMBON
  BATU
  DUMAI
  PONDOKAREN
  PONDOKGEDE
  BLITAR
  PEKANBARU
  RANGKASBITUNG
  PURWAKARTA
  BOJONEGORO
  SELATPANJANG
  SERANG
  SLAWI
  BONDOWOSO
  POLEWALI
  SERPONG
  SUBANG
  GAMPENGREJO
  MAKASAR
  TANGERANG
  SUKABUMI
  GEDANGAN
  PALOPO
  TELUKNAGA
  SUKARAJA
  GRESIK
  PAREPARE
  BENGKULU
  SUMEDANG
  GROGOL
  SOMBAOPU
  GORONTALO
  TAMBUN
  JAMBI
  WATAMPONE
  MANOKWARI
  TAROGONG
  JATI
  PALU
  SORONG
  TASIKMALAYA
  JEMBER
  BAUBAU
  ARJAWINANGUN
  ADIWERNA
  JOMBANG
  KENDARI
  ASTANAJAPURA
  BAE
  KEBOMAS
  BITUNG
  BANDUNG
  BANDUNGBARAT
  BANDUNGKOTA
  BATANG
  KEDIRI
  MANADO
  BANJAR
  BLORA
  KEDUNGWARU
  BUKITTINGGI
  BEKASI
  BREBES
  KEPANJEN
  PADANG
  BOGOR
  BUMIAYU
  LAWANG
  PAYAKUMBUH
  BOJONGGEDE
  CEPU
  LUMAJANG
  BATURAJA
  CAMPEA
  CILACAP
  MADIUN
  LAHAT
  CIAMIS
  COMAL
  MALANG
  LUBUKLINGGAU
  CIANJUR
  DUKUHTURI
  MOJOKERTO
  PALEMBANG
  CIAWI
  JEPARA
  MUNCAR
  PRABUMULIH
  CIBADAK
  KALIWUNGU
  NGANJUK
  TANJUNGAGUNG
  CIBEUREUM
  KARANGANYAR
  PARE
  BELAWAN
  CIBINONG
  KARTOSURO
  PASURUAN
  BINJAI
  CIBITUNG
  KEBUMEN
  PONOROGO
  KABANJAHE
  CIBUNGBULANG
  KEDUNGWUNI
  PORONG
  KISARAN
  CICALENGKA
  KLATEN
  PROBOLINGGO
  KOTAPINANG
  CIKAMPEK
  KRAMAT
  SAMPANG
  MEDAN
  CIKARANG
  KUDUS
  SIDOARJO
  PADANGKOTA
  SIDEMPUAN
  CILEDUG
  MAGELANG
  SINGOSARI
  PEMATANGSIANTAR
  CILEUNGSI
  MERTOYUDAN
  SITUBONDO
  SIBOLGA
  CIMAHI
  MOJOLABAN
  SUMENEP
  SUNGGAL
  CIOMAS
  PANGKAH
  SURABAYA
  TANJUNGBALAI
  CIPARAY
  PATI
  TUBAN
  TANJUNGMORAWA
  PECANGAKAN
  TULUNGAGUNG
  TEBINGTINGGI
  CIREBON
  CIREBONKOTA
  BARAT
  PEKALONGAN
  PONTIANAK
  BANGUNTAPAN
  CISAAT
  PEMALANG
  SINGKAWANG
  BANTUL
  CISARUA
  PETERUKAN
  BANJARBARU
  GAMPING
  CITEUREUP
  PURWODADI
  MARTAPURA
  GODEAN
  DAYEUHKOLOT
  PURWOKERTO
  PALANGKARAYA
  KASIHAN
  DEPOK
  PURWOREJO
  SAMPIT
  KOTABARU
  GARUT
  SALATIGA
  BALIKPAPAN
  SEWON
  INDRAMAYU
  SEMARANG
  BONTANG
  YOGYAKARTA
  JATIWANGI
  SRAGEN
}
