input InternalAgreedDescriptivePhotoInput {
  _id: ObjectID
  photoUrl: String
  description: String
  type: DescriptivePhotoType
  createdAt: Time
  updatedAt: Time
}

type AgreedDescriptivePhoto {
  _id: ObjectID
  photoUrl: String
  description: String
  type: DescriptivePhotoType
  createdAt: Time
  updatedAt: Time
}
