input AgreedProductInput {
  name: String
  description: String
  variants: [AgreedProductVariantInput]
}

input InternalAgreedProductInput {
  name: String
  description: String
  variants: [InternalAgreedProductVariantInput]
  photos: [InternalAgreedDescriptivePhotoInput]
  createdAt: Time
  updatedAt: Time
}

input AgreedProductFilterFields {
  name: StringFilterField
  description: StringFilterField
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type AgreedProduct {
  name: String
  description: String
  variants: [AgreedProductVariant]
  photos: [AgreedDescriptivePhoto]
  createdAt: Time
  updatedAt: Time
}
