enum AccountStatus {
  ACTIVE
  INACTIVE
  RECEIVE_ATTENTION
}

enum AccountType {
  PERSON
  SYSTEM_ENTITY
}

input UpdateOtherAccount {
  _id: ObjectID!
  status: AccountStatus
  statusReason: String
  type: AccountType
  idCard: NewIDCard
}

input CreateAccount {
  _id: ObjectID
  email: String!
  status: AccountStatus
  statusReason: String
  language: Language!
  type: AccountType!
  person: ObjectIDOnly
  deviceTokens: [String!]
  createdAt: Time
  updatedAt: Time
}

input UpdateAccount {
  _id: ObjectID!
  email: String
  language: Language
  type: AccountType
  person: ObjectIDOnly
  deviceTokens: [String!]
  updatedAt: Time
}

input AccountFilterFields {
  _id: ObjectID
  email: String
  status: AccountStatus
  statusReason: String
  type: AccountType
  person: ObjectIDOnly
}

type Account {
  _id: ObjectID!
  email: String!
  status: AccountStatus!
  statusReason: String
  language: Language!
  type: AccountType!
  deviceTokens: [String!]!
  person: Person
  createdAt: Time!
  updatedAt: Time!
}
