enum Gender {
  MALE
  FEMALE
}

input CreatePerson {
  _id: ObjectID
  firstName: String!
  lastName: String!
  gender: Gender
  phoneNumber: String!
}

input DatabaseCreatePerson {
  _id: ObjectID
  firstName: String!
  lastName: String!
  gender: Gender
  phoneNumber: String!
  createdAt: Time
  updatedAt: Time
}

input UpdatePerson {
  _id: ObjectID!
  firstName: String
  lastName: String
  gender: Gender
  phoneNumber: String
}

input DatabaseUpdatePerson {
  _id: ObjectID!
  firstName: String
  lastName: String
  gender: Gender
  phoneNumber: String
  updatedAt: Time
}

type Person {
  _id: ObjectID!
  firstName: String!
  lastName: String!
  gender: Gender
  phoneNumber: String
  idCard: IDCard
  createdAt: Time!
  updatedAt: Time!
}
