enum NotificationCategory {
  MEMBER_ACCESS_INVITATION_REQUEST
  MEMBER_ACCESS_INVITATION_ACCEPTED
  ORG_APPROVAL

  MOU_CREATED
  MOU_UPDATED
  MOU_APPROVED

  PURCHASE_ORDER_SUPPLY_BROADCAST

  INVOICE_CREATED
  INVOICE_UPDATED

  PURCHASE_ORDER_CREATED
  PURCHASE_ORDER_APPROVAL

  PURCHASE_ORDER_ITEM_CREATED
  PURCHASE_ORDER_ITEM_CUSTOMER_AGREED
  PURCHASE_ORDER_ITEM_FULFILLED
  PURCHASE_ORDER_ITEM_APPROVAL
}

type NotificationMessage {
  title: String!
  body: String!
}

input PayloadOptionsInput {
  memberAccessInvitationPayload: MemberAccessInvitationPayloadInput
  purchaseOrderToSupplyBroadcastPayload: PurchaseOrderToSupplyBroadcastPayloadInput
  invoicePayload: InvoicePayloadInput
  mouPayload: MouPayloadInput
  purchaseOrderPayload: PurchaseOrderPayloadInput
  purchaseOrderItemPayload: PurchaseOrderItemPayloadInput
}

type PayloadOptions {
  memberAccessInvitationPayload: MemberAccessInvitationPayload
  purchaseOrderToSupplyBroadcastPayload: PurchaseOrderToSupplyBroadcastPayload
  invoicePayload: InvoicePayload
  mouPayload: MouPayload
  purchaseOrderPayload: PurchaseOrderPayload
  purchaseOrderItemPayload: PurchaseOrderItemPayload
}

input InternalCreateNotification {
  payloadOptions: PayloadOptionsInput!
  notificationCategory: NotificationCategory!
  recipientAccount: ObjectIDOnly!
}

input DatabaseCreateNotification {
  payloadOptions: PayloadOptionsInput!
  notificationCategory: NotificationCategory!
  recipientAccount: AccountForNotifRecipientInput!
  readFlag: Boolean!
  createdAt: Time
  updatedAt: Time
}

input BulkUpdateNotification {
  IDs: [ObjectID!]!
  readFlag: Boolean
}

input InternalBulkUpdateNotification {
  IDs: [ObjectID!]!
  payloadOptions: PayloadOptionsInput
  notificationCategory: NotificationCategory
  recipientAccount: ObjectIDOnly
  readFlag: Boolean
  language: String!
}

input DatabaseUpdateNotification {
  _id: ObjectID!
  payloadOptions: PayloadOptionsInput
  notificationCategory: NotificationCategory
  recipientAccount: AccountForNotifRecipientInput
  readFlag: Boolean
  updatedAt: Time
}

input NotificationFilterFields {
  _id: ObjectID
  notificationCategory: StringFilterField
  recipientAccount: ObjectIDOnlyFilterField
  readFlag: BooleanFilterField
}

type DatabaseNotification {
  _id: ObjectID!
  payloadOptions: PayloadOptions
  notificationCategory: NotificationCategory!
  recipientAccount: AccountForNotifRecipient!
  readFlag: Boolean!
  createdAt: Time
  updatedAt: Time
}

type Notification {
  _id: ObjectID!
  message: NotificationMessage!
  notificationCategory: NotificationCategory!
  recipientAccount: AccountForNotifRecipient!
  readFlag: Boolean!
  createdAt: Time
  updatedAt: Time
}
