enum MemberAccessStatus {
  ACTIVE
  INACTIVE
}

input CreateMemberAccess {
  account: ObjectIDOnly!
  invitationAccepted: Boolean
  organization: AttachOrganizationInput
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  access: MemberAccessRefOptionsInput!
  defaultAccess: ObjectIDOnly
  status: MemberAccessStatus!
  previousEntity: ObjectIDOnly
  correspondingLog: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  approvingAccount: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateMemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean
  organization: AttachOrganizationInput
  organizationMembershipRole: OrganizationMembershipRole
  defaultAccess: ObjectIDOnly
  access: MemberAccessRefOptionsInput
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  approvingAccount: ObjectIDOnly
  correspondingLog: ObjectIDOnly
  updatedAt: Time
}

input MemberAccessFilterFields {
  _id: ObjectID
  invitationAccepted: Boolean
  account: ObjectIDOnly
  organization: AttachOrganizationInput
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType
  access: MemberAccessRefOptionsInput
  defaultAccess: ObjectIDOnly
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  approvingAccount: ObjectIDOnly
  previousEntity: ObjectIDOnly
  correspondingLog: ObjectIDOnly
}

type MemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean!
  account: Account!
  organization: Organization
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  access: MemberAccessRefOptions!
  defaultAccess: MemberAccessRef!
  status: MemberAccessStatus!
  proposalStatus: EntityProposalStatus!
  submittingAccount: Account!
  approvingAccount: Account
  previousEntity: MemberAccess
  correspondingLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
