enum MemberAccessStatus {
  ACTIVE
  INACTIVE
}

input CreateMemberAccess {
  account: ObjectIDOnly!
  invitationAccepted: Boolean
  organization: ObjectIDOnly!
  organizationMembershipRole: OrganizationMembershipRole
  """
  Note:
  the field memberAccessRefType is commonly set to ORGANIZATION_BASED.
  especially when inputting Organization ID
  """
  memberAccessRefType: MemberAccessRefType!
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
}

input InternalCreateMemberAccess {
  _id: ObjectID!
  account: ObjectIDOnly!
  invitationAccepted: Boolean
  organization: InternalUpdateOrganization
  organizationLatestUpdate: AttachOrganizationInput
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  access: MemberAccessRefOptionsInput!
  defaultAccess: InternalUpdateMemberAccessRef
  defaultAccessLatestUpdate: ObjectIDOnly
  status: MemberAccessStatus!
  proposedChanges: UpdateMemberAccess
  recentLog: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateMemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean
  organizationMembershipRole: OrganizationMembershipRole
  access: MemberAccessRefOptionsInput
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  """
  Leave the field empty, will be overriden by server.
  """
  submittingAccount: ObjectIDOnly
  """
  Leave the field empty, will be overriden by server.
  """
  recentApprovingAccount: ObjectIDOnly
}

input InternalUpdateMemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean
  organization: InternalUpdateOrganization
  organizationLatestUpdate: AttachOrganizationInput
  organizationMembershipRole: OrganizationMembershipRole
  defaultAccess: InternalUpdateMemberAccessRef
  defaultAccessLatestUpdate: ObjectIDOnly
  access: MemberAccessRefOptionsInput
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: UpdateMemberAccess
  updatedAt: Time
}

input MemberAccessFilterFields {
  _id: ObjectID
  invitationAccepted: Boolean
  account: ObjectIDOnly
  organization: AttachOrganizationInput
  organizationLatestUpdate: AttachOrganizationInput
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType
  access: MemberAccessRefOptionsInput
  defaultAccess: ObjectIDOnly
  defaultAccessLatestUpdate: ObjectIDOnly
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: MemberAccessFilterFields
  recentLog: ObjectIDOnly
}

type MemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean!
  account: Account!
  organization: Organization
  organizationLatestUpdate: Organization
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  access: MemberAccessRefOptions!
  defaultAccess: MemberAccessRef!
  defaultAccessLatestUpdate: MemberAccessRef
  status: MemberAccessStatus!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: MemberAccess
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
