enum MemberAccessStatus {
  ACTIVE
  INACTIVE
}

input CreateMemberAccess {
  account: ObjectIDOnly!
  invitationAccepted: Boolean
  organization: ObjectIDOnly!
  organizationMembershipRole: OrganizationMembershipRole
  """
  Note:
  the field memberAccessRefType is commonly set to ORGANIZATION_BASED.
  especially when inputting Organization ID
  """
  memberAccessRefType: MemberAccessRefType!
  status: MemberAccessStatus
}

input InternalCreateMemberAccess {
  _id: ObjectID!
  account: ObjectIDOnly!
  invitationAccepted: Boolean
  organization: ObjectIDOnly!
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  status: MemberAccessStatus!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreateMemberAccess {
  _id: ObjectID!
  account: ObjectIDOnly!
  invitationAccepted: Boolean
  organization: OrganizationForMemberAccessInput
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  access: MemberAccessRefOptionsInput!
  defaultAccessLatestUpdate: ObjectIDOnly!
  status: MemberAccessStatus!
  proposedChanges: MemberAccessProposedInput
  recentLog: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateMemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean
  organizationMembershipRole: OrganizationMembershipRole
  access: MemberAccessRefOptionsInput
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdateMemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean
  organizationMembershipRole: OrganizationMembershipRole
  access: MemberAccessRefOptionsInput
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdateMemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean
  organization: OrganizationForMemberAccessInput
  organizationMembershipRole: OrganizationMembershipRole
  defaultAccessLatestUpdate: ObjectIDOnly
  access: MemberAccessRefOptionsInput
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: MemberAccessProposedInput
  updatedAt: Time
}

input MemberAccessFilterFields {
  _id: ObjectID
  invitationAccepted: BooleanFilterField
  account: ObjectIDOnly
  organization: OrganizationForMemberAccessFilterFields
  organizationMembershipRole: StringFilterField
  memberAccessRefType: StringFilterField
  access: MemberAccessRefOptionsInput
  defaultAccessLatestUpdate: ObjectIDOnlyFilterField
  status: StringFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: MemberAccessProposedFilterFields
  recentLog: ObjectIDOnly
}

input InternalMemberAccessFilterFields {
  _id: ObjectID
  invitationAccepted: Boolean
  account: ObjectIDOnly
  organization: OrganizationForMemberAccessInput
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType
  access: MemberAccessRefOptionsInput
  defaultAccessLatestUpdate: ObjectIDOnly
  status: MemberAccessStatus
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: InternalMemberAccessFilterFields
  recentLog: ObjectIDOnly
}

type MemberAccess {
  _id: ObjectID!
  invitationAccepted: Boolean!
  account: Account!
  organization: Organization
  organizationMembershipRole: OrganizationMembershipRole
  memberAccessRefType: MemberAccessRefType!
  access: MemberAccessRefOptions!
  defaultAccessLatestUpdate: MemberAccessRef!
  status: MemberAccessStatus!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: MemberAccessProposed
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
