extend type Mutation {
  login(deviceToken: String!): Account!
  logout(deviceToken: String!): Account!
  updateAccount(updateAccount: UpdateAccount!): Account!
}

extend type Query {
  account(filterFields: AccountFilterFields!): Account!
  person(account: ObjectIDOnly): Person!
}
