extend type Mutation {
  login(deviceToken: String): Account!
  logout(deviceToken: String): Account!
  createOrganization(createOrganization: CreateOrganization!): Organization!
}

extend type Query {
  user: Person!
}
