extend type Mutation {
  login(deviceToken: String): Account!
  logout(deviceToken: String): Account!
  createOrganization(newOrganization: NewOrganization!): Organization!
}

extend type Query {
  user: PersonDetailed!
}
