
input ManageOrganizationMemberAccessInput {
    manageOrganizationMemberRead: Boolean
    manageOrganizationMemberInvite: Boolean
    manageOrganizationMemberRemove: Boolean
}

type ManageOrganizationMemberAccess {
    manageOrganizationMemberRead: Boolean
    manageOrganizationMemberInvite: Boolean
    manageOrganizationMemberRemove: Boolean
}