enum OrganizationType {
  PARTNER
  CUSTOMER
  INTERNAL
}

input CreateOrganization {
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  profilePhotos: [CreateDescriptivePhoto]
  taggings: [CreateTagging]
  addresses: [CreateAddress]
  taxIdentification: NewIDCard
}

input InternalCreateOrganization {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  profilePhotos: [InternalCreateDescriptivePhoto]
  taggings: [InternalCreateTagging]
  addresses: [InternalCreateAddress]
  taxIdentification: NewIDCard
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreateOrganization {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  point: Int
  unfinalizedPoint: Int
  profilePhotos: [ObjectIDOnly]
  taggings: [ObjectIDOnly]
  addresses: [ObjectIDOnly]
  taxIdentification: NewIDCard
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateOrganization
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateOrganization {
  _id: ObjectID!
  name: String
  phoneNumber: String
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  unfinalizedPoint: Int
  profilePhotos: [UpdateDescriptivePhoto]
  taggings: [UpdateTagging]
  addresses: [UpdateAddress]
  taxIdentification: UpdateIDCard
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdateOrganization {
  _id: ObjectID!
  name: String
  phoneNumber: String
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  unfinalizedPoint: Int
  profilePhotos: [InternalUpdateDescriptivePhoto]
  taggings: [InternalUpdateTagging]
  addresses: [InternalUpdateAddress]
  taxIdentification: UpdateIDCard
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdateOrganization {
  _id: ObjectID!
  name: String
  phoneNumber: String
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  unfinalizedPoint: Int
  profilePhotos: [ObjectIDOnly]
  taggings: [ObjectIDOnly]
  addresses: [ObjectIDOnly]
  taxIdentification: UpdateIDCard
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: DatabaseUpdateOrganization
  updatedAt: Time
}

input OrganizationFilterFields {
  _id: ObjectID
  name: StringFilterField
  phoneNumber: StringFilterField
  type: StringFilterField
  taggings: ObjectIDOnly
  addresses: ObjectIDOnly
  creditAllowance: IntFilterField
  rating: Float
  ratingDescription: StringFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: OrganizationFilterFields
  recentLog: ObjectIDOnly
}

type Organization {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  point: Int!
  unfinalizedPoint: Int!
  profilePhotos: [DescriptivePhoto]
  taggings: [Tagging]
  addresses: [Address]
  taxIdentification: IDCard
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: Organization
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
