enum OrganizationType {
  PARTNER
  CUSTOMER
  INTERNAL
}

input CreateOrganization {
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  point: Int
  unfinalizedPoint: Int
  profilePhotos: [CreateDescriptivePhoto]
  taxIdentification: NewIDCard
  proposalStatus: EntityProposalStatus
}

input InternalCreateOrganization {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  point: Int
  unfinalizedPoint: Int
  profilePhotos: [ObjectIDOnly]
  taxIdentification: NewIDCard
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: UpdateOrganization
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateOrganization {
  _id: ObjectID!
  name: String
  phoneNumber: String
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  unfinalizedPoint: Int
  profilePhotos: [UpdateDescriptivePhoto]
  taxIdentification: UpdateIDCard
  proposalStatus: EntityProposalStatus
}

input InternalUpdateOrganization {
  _id: ObjectID!
  name: String
  phoneNumber: String
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  unfinalizedPoint: Int
  profilePhotos: [ObjectIDOnly]
  taxIdentification: UpdateIDCard
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: UpdateOrganization
  updatedAt: Time
}

input AttachOrganizationInput {
  _id: ObjectID
  type: OrganizationType
}

input OrganizationFilterFields {
  _id: ObjectID
  name: String
  phoneNumber: String
  type: OrganizationType
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: ObjectIDOnly
  recentLog: ObjectIDOnly
}

type Organization {
  _id: ObjectID!
  name: String!
  phoneNumber: String!
  type: OrganizationType!
  creditAllowance: Int
  rating: Float
  ratingDescription: String
  point: Int!
  unfinalizedPoint: Int!
  profilePhotos: [DescriptivePhoto]
  taxIdentification: IDCard
  proposalStatus: EntityProposalStatus!
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: Organization
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
