input CreateOrgProfileDescriptivePhoto {
  photo: Upload!
  photoUrl: String
  description: String
  category: DescriptivePhotoCategory!
  type: String!
  organization: ObjectIDOnly!
}

input UpdateOrgProfileDescriptivePhoto {
  _id: ObjectID!
  photo: Upload
  photoUrl: String
  description: String
  isActive: Boolean
  type: String
}

type OrgProfileDescriptivePhoto implements iDescriptivePhoto {
  _id: ObjectID!
  photoUrl: String!
  description: String
  category: DescriptivePhotoCategory!
  type: String!
  organization: Organization!
}
