enum PurchaseOrderToSupplyStatus {
  CUMMULATING
  OPEN
  FULFILLED
}

input CreatePurchaseOrderToSupply {
  quantityRequested: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  tags: [TagForPurchaseOrderToSupplyInput]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  status: PurchaseOrderToSupplyStatus
}

input InternalCreatePurchaseOrderToSupply {
  quantityRequested: Int!
  quantityFulfilled: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  tags: [TagForPurchaseOrderToSupplyInput]
  purchaseOrderItems: [InternalCreatePurchaseOrderItem]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  status: PurchaseOrderToSupplyStatus
}

input DatabaseCreatePurchaseOrderToSupply {
  quantityRequested: Int!
  quantityFulfilled: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  tags: [TagForPurchaseOrderToSupplyInput]
  purchaseOrderItems: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  status: PurchaseOrderToSupplyStatus
  createdAt: Time!
  updatedAt: Time!
}

input UpdatePurchaseOrderToSupply {
  _id: ObjectID!
  quantityRequested: Int
  quantityFulfilled: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  tags: [TagForPurchaseOrderToSupplyInput]
  purchaseOrderItems: [UpdatePurchaseOrderItem]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  status: PurchaseOrderToSupplyStatus
}

input InternalUpdatePurchaseOrderToSupply {
  _id: ObjectID!
  quantityRequested: Int
  quantityFulfilled: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  tags: [TagForPurchaseOrderToSupplyInput]
  purchaseOrderItems: [InternalUpdatePurchaseOrderItem]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  status: PurchaseOrderToSupplyStatus
}

input DatabaseUpdatePurchaseOrderToSupply {
  _id: ObjectID!
  quantityRequested: Int
  quantityFulfilled: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  tags: [TagForPurchaseOrderToSupplyInput]
  purchaseOrderItems: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  status: PurchaseOrderToSupplyStatus
  updatedAt: Time
}

input PurchaseOrderToSupplyFilterFields {
  _id: ObjectID
  quantityRequested: IntFilterField
  quantityFulfilled: IntFilterField
  productVariant: ProductVariantFilterFields
  timeSlot: StringFilterField
  expectedArrivalDate: TimeFilterField
  tags: ObjectIDOnlyFilterField
  purchaseOrderItems: ObjectIDOnlyFilterField
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyFilterFields
  status: StringFilterField
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type PurchaseOrderToSupply {
  _id: ObjectID!
  quantityRequested: Int!
  quantityFulfilled: Int!
  productVariant: ProductVariantForPurchaseOrderItem!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  tags: [TagForPurchaseOrderToSupply]!
  purchaseOrderItems: [PurchaseOrderItem]!
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupply!
  status: PurchaseOrderToSupplyStatus
  createdAt: Time!
  updatedAt: Time!
}
