input CreatePurchaseOrderToSupply {
  totalQuantity: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tag: [ObjectID]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
}

input InternalCreatePurchaseOrderToSupply {
  totalQuantity: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tag: [ObjectID]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
}

input DatabaseCreatePurchaseOrderToSupply {
  totalQuantity: Int!
  quantityToSupply: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tag: [ObjectID]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  createdAt: Time!
  updatedAt: Time!
}

input UpdatePurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int
  quantityToSupply: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  expectedDeliverySchedule: ExpectedDeliverySchedule
  tag: [ObjectID]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
}

input InternalUpdatePurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int
  quantityToSupply: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  expectedDeliverySchedule: ExpectedDeliverySchedule
  tag: [ObjectID]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
}

input DatabaseUpdatePurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int
  quantityToSupply: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  expectedDeliverySchedule: ExpectedDeliverySchedule
  tag: [ObjectID]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  updatedAt: Time
}

input PurchaseOrderToSupplyFilterFields {
  _id: ObjectID
  totalQuantity: IntFilterField
  quantityToSupply: IntFilterField
  productVariant: ProductVariantFilterFields
  expectedDeliverySchedule: StringFilterField
  tag: ObjectIDFilterField
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyFilterFields
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type PurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int!
  quantityToSupply: Int!
  productVariant: ProductVariantForPurchaseOrderItem!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tag: [Tag]!
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupply!
  createdAt: Time!
  updatedAt: Time!
}
