enum PurchaseOrderToSupplyStatus {
  CUMMULATING
  PROCESSED
}

input CreatePurchaseOrderToSupply {
  totalQuantity: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tags: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  status: PurchaseOrderToSupplyStatus
}

input InternalCreatePurchaseOrderToSupply {
  totalQuantity: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tags: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  status: PurchaseOrderToSupplyStatus
}

input DatabaseCreatePurchaseOrderToSupply {
  totalQuantity: Int!
  quantityToSupply: Int!
  productVariant: ProductVariantForPurchaseOrderItemInput!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tags: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput!
  status: PurchaseOrderToSupplyStatus
  createdAt: Time!
  updatedAt: Time!
}

input UpdatePurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int
  quantityToSupply: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  expectedDeliverySchedule: ExpectedDeliverySchedule
  tags: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  status: PurchaseOrderToSupplyStatus
}

input InternalUpdatePurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int
  quantityToSupply: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  expectedDeliverySchedule: ExpectedDeliverySchedule
  tags: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  status: PurchaseOrderToSupplyStatus
}

input DatabaseUpdatePurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int
  quantityToSupply: Int
  productVariant: ProductVariantForPurchaseOrderItemInput
  expectedDeliverySchedule: ExpectedDeliverySchedule
  tags: [ObjectIDOnly]
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyInput
  status: PurchaseOrderToSupplyStatus
  updatedAt: Time
}

input PurchaseOrderToSupplyFilterFields {
  _id: ObjectID
  totalQuantity: IntFilterField
  quantityToSupply: IntFilterField
  productVariant: ProductVariantFilterFields
  expectedDeliverySchedule: StringFilterField
  tags: ObjectIDOnlyFilterField
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupplyFilterFields
  status: StringFilterField
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type PurchaseOrderToSupply {
  _id: ObjectID!
  totalQuantity: Int!
  quantityToSupply: Int!
  productVariant: ProductVariantForPurchaseOrderItem!
  expectedDeliverySchedule: ExpectedDeliverySchedule!
  tags: [Tag]!
  addressRegionGroup: AddressRegionGroupForPurchaseOrderToSupply!
  status: PurchaseOrderToSupplyStatus
  createdAt: Time!
  updatedAt: Time!
}
