enum PickUpStatus {
  ADDRESS_NOTED
  DRIVER_ASSIGNED
  PICKING_UP
  PICKED_UP
}

input CreateSupplyOrderItemPickUp {
  address: ObjectIDOnly!
  scheduledPickUpTime: Time!
  note: String
}

input InternalCreateSupplyOrderItemPickUp {
  address: ObjectIDOnly!
  scheduledPickUpTime: Time!
  note: String
}

input UpdateSupplyOrderItemPickUp {
  address: ObjectIDOnly
  scheduledPickUpTime: Time
  note: String
}

input UpdateSupplyOrderItemPickUpByInternal {
  photos: [UpdateDescriptivePhoto]
  courier: ObjectIDOnly
  startedPickingUp: Boolean
  finishedPickingUp: Boolean
  courierResponded: Boolean
  noOfPackages: Int
}

input InternalUpdateSupplyOrderItemPickUp {
  address: AddressForSupplyOrderItemInput
  photos: [InternalUpdateDescriptivePhoto]
  courier: AccountForSupplyOrderItemInput
  scheduledPickUpTime: Time
  startedPickingUp: Boolean
  finishedPickingUp: Boolean
  note: String
  courierResponded: Boolean
  noOfPackages: Int
}

input DatabaseSupplyOrderItemPickUp {
  publicId: String
  address: AddressForSupplyOrderItemInput
  photos: [ObjectIDOnly]
  courier: AccountForSupplyOrderItemInput
  scheduledPickUpTime: Time
  startPickUpTime: Time
  finishPickUpTime: Time
  status: PickUpStatus
  note: String
  noOfPackages: Int
}

input SupplyOrderItemPickUpFilterFields {
  publicId: StringFilterField
  note: StringFilterField
  address: AddressForSupplyOrderItemFilterFields
  courier: AccountForSupplyOrderItemFilterFields
  scheduledPickUpTime: TimeFilterField
  startPickUpTime: TimeFilterField
  finishPickUpTime: TimeFilterField
  status: StringFilterField
  noOfPackages: IntFilterField
}

type SupplyOrderItemPickUp {
  publicId: String
  address: AddressForSupplyOrderItem
  photos: [DescriptivePhoto]
  courier: AccountForSupplyOrderItem
  scheduledPickUpTime: Time
  startPickUpTime: Time
  finishPickUpTime: Time
  status: PickUpStatus!
  note: String
  noOfPackages: Int
}
