enum MemberAccessRefType {
    ORGANIZATIONS_BASED
    ACCOUNTS_BASICS
}

input MemberAccessRefOptionsInput {
    account: AccountAccessInput
    manageOrganizationMember: ManageOrganizationMemberAccessInput
    requestOrganization: RequestOrganizationAccessInput
    viewOrganization: ViewOrganizationAccessInput
}

type MemberAccessRefOptions {
    account: AccountAccess
    manageOrganizationMember: ManageOrganizationMemberAccess
    requestOrganization: RequestOrganizationAccess
    viewOrganization: ViewOrganizationAccess
}

input CreateMemberAccessRef {
    access: MemberAccessRefOptionsInput!
    memberAccessRefType: MemberAccessRefType!
    organizationMembershipRole: OrganizationMembershipRole
    organizationType: OrganizationType
    proposalStatus: EntityProposalStatus
    submittingPerson: ObjectIDOnly!
    createdAt: Time
    updatedAt: Time
}

input UpdateMemberAccessRef {
    _id: ObjectID!
    access: MemberAccessRefOptionsInput
    memberAccessRefType: MemberAccessRefType
    organizationMembershipRole: OrganizationMembershipRole
    organizationType: OrganizationType
    proposalStatus: EntityProposalStatus
    approvingPerson: ObjectIDOnly
    updatedAt: Time
}

type MemberAccessRef {
    _id: ObjectID!
    access: MemberAccessRefOptions!
    memberAccessRefType: MemberAccessRefType!
    organizationMembershipRole: OrganizationMembershipRole
    organizationType: OrganizationType
    proposalStatus: EntityProposalStatus!
    submittingPerson: Person!
    approvingPerson: Person
    createdAt: Time!
    updatedAt: Time!
}