input PartyInput {
  organization: ObjectIDOnly!
  accountInCharge: ObjectIDOnly
  signature: SignatureInput
}

input InternalPartyInput {
  organization: OrganizationForPartyInput!
  accountInCharge: AccountForPartyInput
  signature: InternalSignatureInput
  createdAt: Time
  updatedAt: Time
}

input PartyFilterFields {
  organization: OrganizationForPartyFilterFields
  accountInCharge: AccountForPartyFilterFields
  signature: SignatureFilterFields
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type Party {
  organization: OrganizationForParty!
  accountInCharge: AccountForParty
  signature: Signature
  createdAt: Time
  updatedAt: Time
}
