input CreateProduct {
  name: String!
  description: String
  isActive: Boolean
  photos: [CreateDescriptivePhoto]
  variants: [CreateProductVariant]
  taggings: [CreateTagging]
  proposalStatus: EntityProposalStatus
}

input InternalCreateProduct {
  _id: ObjectID!
  name: String!
  description: String
  isActive: Boolean
  photos: [InternalCreateDescriptivePhoto]
  variants: [InternalCreateProductVariant]
  taggings: [InternalCreateTagging]
  syncedWithES: Boolean!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: InternalUpdateProduct
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input DatabaseCreateProduct {
  _id: ObjectID!
  name: String!
  description: String
  isActive: Boolean
  photos: [ObjectIDOnly]
  variants: [ObjectIDOnly]
  taggings: [ObjectIDOnly]
  syncedWithES: Boolean!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateProduct
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateProduct {
  _id: ObjectID!
  name: String
  description: String
  isActive: Boolean
  """
  Leave the field null/empty array or fill it with updates to the product's photos.
  (a) If ID is present, then it will be update operation(s) to existing photos.
  (b) If ID is not present, then it will be additional photo(s)
   appended to the list of product's photos.
  """
  photos: [UpdateDescriptivePhoto]
  variants: [UpdateProductVariant]
  taggings: [UpdateTagging]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  """
  Leave the field empty, will be overriden by server.
  """
  submittingAccount: ObjectIDOnly
  """
  Leave the field empty, will be overriden by server.
  """
  recentApprovingAccount: ObjectIDOnly
}

input InternalUpdateProduct {
  _id: ObjectID!
  name: String
  description: String
  isActive: Boolean
  photos: [InternalUpdateDescriptivePhoto]
  variants: [InternalUpdateProductVariant]
  taggings: [InternalUpdateTagging]
  syncedWithES: Boolean
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: InternalUpdateProduct
  recentLog: ObjectIDOnly
}

input DatabaseUpdateProduct {
  _id: ObjectID!
  name: String
  description: String
  isActive: Boolean
  photos: [ObjectIDOnly]
  variants: [ObjectIDOnly]
  taggings: [ObjectIDOnly]
  syncedWithES: Boolean
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateProduct
  recentLog: ObjectIDOnly
  updatedAt: Time
}

input ProductFilterFields {
  _id: ObjectID
  name: StringFilterField
  description: StringFilterField
  isActive: BooleanFilterField
  taggings: ObjectIDOnly
  syncedWithES: BooleanFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: ProductFilterFields
  recentLog: ObjectIDOnly
}

type Product {
  _id: ObjectID!
  name: String!
  description: String
  isActive: Boolean!
  photos: [DescriptivePhoto]
  variants: [ProductVariant]
  taggings: [Tagging]
  syncedWithES: Boolean!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: Product
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
