input CreateProduct {
  name: String!
  description: String
  priceRange: String
  isActive: Boolean
  photos: [ObjectIDOnly]
  variants: [ObjectIDOnly]
}

input UpdateProduct {
  _id: ObjectID!
  name: String
  description: String
  priceRange: String
  isActive: Boolean
}

input InternalUpdateProduct {
  _id: ObjectID!
  name: String
  description: String
  priceRange: String
  isActive: Boolean
  photos: [ObjectIDOnly]
  variants: [ObjectIDOnly]
}

type Product {
  _id: ObjectID!
  name: String!
  description: String
  priceRange: String
  isActive: Boolean!
  photos: [ProductDescriptivePhoto]
  variants: [ProductVariant]
}
