
input AccountAccessesInput {
    accountReadOwned: Boolean
    accountRead: Boolean
    accountLogin: Boolean
    accountAcceptInvitation: Boolean
    accountUpdate: Boolean
    accountUpdateOwned: Boolean
}

type AccountAccesses {
    accountReadOwned: Boolean
    accountRead: Boolean
    accountLogin: Boolean
    accountAcceptInvitation: Boolean
    accountUpdate: Boolean
    accountUpdateOwned: Boolean
}