
input AccountAccessesInput {
    accountViewProfile: Boolean
    accountLogin: Boolean
    accountAcceptInvitation: Boolean
}

type AccountAccesses {
    accountViewProfile: Boolean
    accountLogin: Boolean
    accountAcceptInvitation: Boolean
}