input MemberAccessRefAccessesInput {
  memberAccessRefApproval: Boolean
  memberAccessRefRead: Boolean
  memberAccessRefCreate: Boolean
  memberAccessRefUpdate: Boolean
  memberAccessRefReadAll: Boolean
}

type MemberAccessRefAccesses {
  memberAccessRefApproval: Boolean
  memberAccessRefRead: Boolean
  memberAccessRefCreate: Boolean
  memberAccessRefUpdate: Boolean
  memberAccessRefReadAll: Boolean
}
