
input ManageMemberAccessesInput {
    manageMemberAccessRead: Boolean
    manageMemberAccessInvite: Boolean
    manageMemberAccessRemove: Boolean
}

type ManageMemberAccesses {
    manageMemberAccessRead: Boolean
    manageMemberAccessInvite: Boolean
    manageMemberAccessRemove: Boolean
}