
input ManageMemberAccessesInput {
    memberAccessCreate: Boolean
    memberAccessRead: Boolean
    memberAccessUpdate: Boolean
    memberAccessApproval: Boolean
}

type ManageMemberAccesses {
    memberAccessCreate: Boolean
    memberAccessRead: Boolean
    memberAccessUpdate: Boolean
    memberAccessApproval: Boolean
}