input OrganizationAccessesInput {
  organizationApproval: Boolean
  organizationRead: Boolean
  organizationCreate: Boolean
  organizationUpdate: Boolean
  organizationReadAll: Boolean
}

type OrganizationAccesses {
  organizationApproval: Boolean
  organizationRead: Boolean
  organizationCreate: Boolean
  organizationUpdate: Boolean
  organizationReadAll: Boolean
}
