input PaymentAccessesInput {
  paymentCreate: Boolean
  paymentUpdate: Boolean
  paymentReadAll: Boolean
  paymentReadOwned: Boolean
  paymentApproval: Boolean
}

type PaymentAccesses {
  paymentCreate: Boolean
  paymentUpdate: Boolean
  paymentReadAll: Boolean
  paymentReadOwned: Boolean
  paymentApproval: Boolean
}
