input PurchaseOrderItemDeliveryAccessesInput {
  purchaseOrderItemDeliveryUpdate: Boolean
  purchaseOrderItemDeliveryAssignDriver: Boolean
}

type PurchaseOrderItemDeliveryAccesses {
  purchaseOrderItemDeliveryUpdate: Boolean
  purchaseOrderItemDeliveryAssignDriver: Boolean
}
