input SupplyOrderItemPickUpAccessesInput {
  supplyOrderItemPickUpUpdate: Boolean
  supplyOrderItemPickUpAssignDriver: Boolean
}

type SupplyOrderItemPickUpAccesses {
  supplyOrderItemPickUpUpdate: Boolean
  supplyOrderItemPickUpAssignDriver: Boolean
}
