input TagAccessesInput {
  tagCreate: Boolean
  tagUpdate: Boolean
  tagReadAll: Boolean
  tagApproval: Boolean
}

type TagAccesses {
  tagCreate: Boolean
  tagUpdate: Boolean
  tagReadAll: Boolean
  tagApproval: Boolean
}
