input AddressRegionGroupForAddressInput {
  _id: ObjectID!
  publicId: String!
}

input AddressRegionGroupForAddressFilterFields {
  _id: ObjectID
  publicId: StringFilterField
}

type AddressRegionGroupForAddress {
  _id: ObjectID!
  publicId: String!
}
