input ResolvedGeocodingInput {
  province: String
  district: String
  municipality: City
  zipCode: String
  streetName: String
}

type ResolvedGeocoding {
  province: String
  district: String
  municipality: City
  zipCode: String
  streetName: String
}
