input ResolvedGeocodingInput {
  province: String
  district: String
  municipality: String
  zipCode: String
  streetName: String
}

input ResolvedGeocodingFilterFields {
  province: StringFilterField
  district: StringFilterField
  municipality: StringFilterField
  zipCode: StringFilterField
  streetName: StringFilterField
}

type ResolvedGeocoding {
  province: String
  district: String
  municipality: String
  zipCode: String
  streetName: String
}
