enum DeliveryTimeSlot {
  """
  4AM to 6AM
  """
  DAWN
  """
  6.01AM to 8AM
  """
  MORNING
  """
  10.01AM to 12PM
  """
  NOON
  """
  12.01PM to 2PM
  """
  AFTERNOON
}

enum DeliveryStatus {
  ADDRESS_NOTED
  DRIVER_ASSIGNED
  IN_DELIVERY
  DELIVERED
}

input CreatePurchaseOrderItemDelivery {
  address: ObjectIDOnly!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  note: String
}

input DatabaseCreatePurchaseOrderItemDelivery {
  address: AddressForPurchaseOrderItemInput!
  photos: [ObjectIDOnly]!
  courier: AccountForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  actualDeliveryTime: Time
  status: DeliveryStatus!
  note: String
  courierResponded: Boolean!
}

input UpdatePurchaseOrderItemDelivery {
  address: ObjectIDOnly
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  note: String
}

input UpdatePurchaseOrderItemDeliveryByInternal {
  photos: [UpdateDescriptivePhoto]
  courier: ObjectIDOnly
  actualDeliveryTime: Time
  courierResponded: Boolean
  noOfPackages: Int
}

input InternalPurchaseOrderItemDelivery {
  publicId: String
  address: AddressForPurchaseOrderItemInput
  photos: [InternalUpdateDescriptivePhoto]
  courier: AccountForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  actualDeliveryTime: Time
  status: DeliveryStatus
  note: String
  courierResponded: Boolean
  noOfPackages: Int
}

input DatabaseUpdatePurchaseOrderItemDelivery {
  publicId: String
  address: AddressForPurchaseOrderItemInput
  photos: [ObjectIDOnly]
  courier: AccountForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  actualDeliveryTime: Time
  status: DeliveryStatus
  note: String
  courierResponded: Boolean
  noOfPackages: Int
}

input PurchaseOrderItemDeliveryFilterFields {
  publicId: StringFilterField
  note: StringFilterField
  address: AddressForPurchaseOrderItemFilterFields
  courier: AccountForPurchaseOrderItemFilterFields
  timeSlot: StringFilterField
  expectedArrivalDate: TimeFilterField
  actualDeliveryTime: TimeFilterField
  status: StringFilterField
  courierResponded: BooleanFilterField
  noOfPackages: IntFilterField
}

type PurchaseOrderItemDelivery {
  publicId: String
  address: AddressForPurchaseOrderItem!
  photos: [DescriptivePhoto]
  courier: AccountForPurchaseOrderItem
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  actualDeliveryTime: Time
  status: DeliveryStatus!
  note: String
  courierResponded: Boolean!
  noOfPackages: Int
}
