enum DeliveryTimeSlot {
  """
  4AM to 6AM
  """
  DAWN
  """
  6.01AM to 8AM
  """
  MORNING
  """
  10.01AM to 12PM
  """
  NOON
  """
  12.01PM to 2PM
  """
  AFTERNOON
}

enum DeliveryStatus {
  ADDRESS_NOTED
  DRIVER_ASSIGNED
  DELIVERING
  DELIVERED
}

input CreatePurchaseOrderItemDelivery {
  address: ObjectIDOnly!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  note: String
}

input InternalCreatePurchaseOrderItemDelivery {
  address: ObjectIDOnly!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  note: String
}

input UpdatePurchaseOrderItemDelivery {
  address: ObjectIDOnly
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  note: String
}

input UpdatePurchaseOrderItemDeliveryByInternal {
  photosAfterReceived: [UpdateDescriptivePhoto]
  photos: [UpdateDescriptivePhoto]
  courier: ObjectIDOnly
  startedDelivering: Boolean
  finishedDelivering: Boolean
  courierResponded: Boolean
  noOfPackages: Int
}

input InternalUpdatePurchaseOrderItemDelivery {
  address: AddressForPurchaseOrderItemInput
  photosAfterReceived: [InternalUpdateDescriptivePhoto]
  photos: [InternalUpdateDescriptivePhoto]
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  courier: ObjectIDOnly
  startedDelivering: Boolean
  finishedDelivering: Boolean
  note: String
  courierResponded: Boolean
  noOfPackages: Int
}

input DatabasePurchaseOrderItemDelivery {
  publicId: String
  address: AddressForPurchaseOrderItemInput
  photosAfterReceived: [ObjectIDOnly]
  photos: [ObjectIDOnly]
  courier: AccountForPurchaseOrderItemInput
  timeSlot: DeliveryTimeSlot
  expectedArrivalDate: Time
  startDeliveryTime: Time
  finishDeliveryTime: Time
  status: DeliveryStatus
  note: String
  noOfPackages: Int
}

input PurchaseOrderItemDeliveryFilterFields {
  publicId: StringFilterField
  note: StringFilterField
  address: AddressForPurchaseOrderItemFilterFields
  courier: AccountForPurchaseOrderItemFilterFields
  timeSlot: StringFilterField
  expectedArrivalDate: TimeFilterField
  startDeliveryTime: TimeFilterField
  finishDeliveryTime: TimeFilterField
  status: StringFilterField
  noOfPackages: IntFilterField
}

type PurchaseOrderItemDelivery {
  publicId: String
  address: AddressForPurchaseOrderItem!
  photosAfterReceived: [DescriptivePhoto]
  photos: [DescriptivePhoto]
  courier: AccountForPurchaseOrderItem
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  startDeliveryTime: Time
  finishDeliveryTime: Time
  status: DeliveryStatus!
  note: String
  noOfPackages: Int
}
