enum PurchaseOrderItemStatus {
  PENDING_CONFIRMATION
  AWAITING_FULFILLMENT
  PARTIALLY_FULFILLED
  FULLFILLED
  CANCELLED
}

input CreatePurchaseOrderItem {
  quantity: Int!
  note: String
  mouItem: ObjectIDOnly
  productVariant: ObjectIDOnly!
  deliveryDetail: CreatePurchaseOrderItemDelivery
  proposalStatus: EntityProposalStatus
}

input InternalCreatePurchaseOrderItem {
  _id: ObjectID
  quantity: Int!
  unitPrice: Int!
  subTotal: Int
  salesAmount: Int
  note: String
  mouItem: MouItemForPurchaseOrderItemInput
  productVariant: ProductVariantForPurchaseOrderItemInput!
  deliveryDetail: InternalPurchaseOrderItemDelivery
  customerAgreed: Boolean
  purchaseOrder: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: InternalUpdatePurchaseOrderItem
  recentLog: ObjectIDOnly
}

input DatabaseCreatePurchaseOrderItem {
  _id: ObjectID!
  quantity: Int!
  quantityFulfilled: Int!
  unitPrice: Int!
  subTotal: Int!
  salesAmount: Int!
  note: String
  mouItem: MouItemForPurchaseOrderItemInput
  productVariant: ProductVariantForPurchaseOrderItemInput!
  deliveryDetail: DatabaseCreatePurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus
  customerAgreed: Boolean!
  purchaseOrder: ObjectIDOnly!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdatePurchaseOrderItem
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdatePurchaseOrderItemDeliveryOnly {
  _id: ObjectID!
  deliveryDetail: UpdatePurchaseOrderItemDeliveryByInternal
}

input UpdatePurchaseOrderItem {
  """
  Note: ID is optional in here. (a) If present, an update will occur when submitting the request.
  (b) If not present, the request will create new object.
  """
  _id: ObjectID
  quantity: Int
  quantityFulfilled: Int
  unitPrice: Int
  subTotal: Int
  note: String
  mouItem: ObjectIDOnly
  productVariant: ObjectIDOnly
  deliveryDetail: UpdatePurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus
  customerAgreed: Boolean
  purchaseOrder: ObjectIDOnly
  purchaseOrderItemReturn: UpdatePurchaseOrderItemReturn
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  """
  Leave the field empty, will be overriden by server.
  """
  submittingAccount: ObjectIDOnly
  """
  Leave the field empty, will be overriden by server.
  """
  recentApprovingAccount: ObjectIDOnly
}

input InternalUpdatePurchaseOrderItem {
  _id: ObjectID
  quantity: Int
  quantityFulfilled: Int
  unitPrice: Int
  subTotal: Int
  salesAmount: Int
  note: String
  mouItem: MouItemForPurchaseOrderItemInput
  productVariant: ProductVariantForPurchaseOrderItemInput
  deliveryDetail: InternalPurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus
  customerAgreed: Boolean
  purchaseOrder: ObjectIDOnly
  purchaseOrderToSupply: ObjectIDOnly
  purchaseOrderItemReturn: InternalPurchaseOrderItemReturn
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: InternalUpdatePurchaseOrderItem
}

input DatabaseUpdatePurchaseOrderItem {
  _id: ObjectID!
  quantity: Int
  quantityFulfilled: Int
  unitPrice: Int
  subTotal: Int
  salesAmount: Int
  note: String
  mouItem: MouItemForPurchaseOrderItemInput
  productVariant: ProductVariantForPurchaseOrderItemInput
  deliveryDetail: DatabaseUpdatePurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus
  customerAgreed: Boolean
  purchaseOrder: ObjectIDOnly
  purchaseOrderToSupply: ObjectIDOnly
  purchaseOrderItemReturn: DatabaseUpdatePurchaseOrderItemReturn
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: DatabaseUpdatePurchaseOrderItem
  updatedAt: Time
}

input PurchaseOrderItemFilterFields {
  _id: ObjectID
  quantity: IntFilterField
  quantityFulfilled: IntFilterField
  unitPrice: IntFilterField
  subTotal: IntFilterField
  salesAmount: IntFilterField
  note: StringFilterField
  mouItem: ObjectIDOnly
  productVariant: ObjectIDOnly
  expectedDeliverySchedule: StringFilterField
  deliveryDetail: PurchaseOrderItemDeliveryFilterFields
  status: StringFilterField
  customerAgreed: BooleanFilterField
  purchaseOrder: ObjectIDOnlyFilterField
  purchaseOrderToSupply: ObjectIDOnlyFilterField
  purchaseOrderItemReturn: PurchaseOrderItemReturnFilterFields
  proposalStatus: StringFilterField
  proposalStatusReason: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: PurchaseOrderItemFilterFields
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type PurchaseOrderItem {
  _id: ObjectID!
  quantity: Int!
  quantityFulfilled: Int!
  unitPrice: Int!
  subTotal: Int!
  salesAmount: Int!
  note: String
  mouItem: MouItemForPurchaseOrderItem
  productVariant: ProductVariantForPurchaseOrderItem!
  deliveryDetail: PurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus!
  customerAgreed: Boolean!
  purchaseOrder: PurchaseOrder
  purchaseOrderToSupply: PurchaseOrderToSupply
  purchaseOrderItemReturn: PurchaseOrderItemReturn!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: PurchaseOrderItem
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
