input PurchaseOrderItemProposedInput {
  _id: ObjectID!
  quantity: Int
  quantityFulfilled: Int
  unitPrice: Int
  subTotal: Int
  salesAmount: Int
  note: String
  mouItem: MouItemForPurchaseOrderItemInput
  productVariant: ProductVariantForPurchaseOrderItemInput
  deliveryDetail: DatabasePurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus
  customerAgreed: Boolean
  purchaseOrder: ObjectIDOnly
  purchaseOrderToSupply: ObjectIDOnly
  purchaseOrderItemReturn: DatabaseUpdatePurchaseOrderItemReturn
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input PurchaseOrderItemProposedFilterFields {
  _id: ObjectIDFilterField
  quantity: IntFilterField
  quantityFulfilled: IntFilterField
  unitPrice: IntFilterField
  subTotal: IntFilterField
  salesAmount: IntFilterField
  note: StringFilterField
  mouItem: ObjectIDOnly
  productVariant: ObjectIDOnly
  expectedDeliverySchedule: StringFilterField
  deliveryDetail: PurchaseOrderItemDeliveryFilterFields
  status: StringFilterField
  customerAgreed: BooleanFilterField
  purchaseOrder: ObjectIDOnlyFilterField
  purchaseOrderToSupply: ObjectIDOnlyFilterField
  purchaseOrderItemReturn: PurchaseOrderItemReturnFilterFields
  proposalStatus: StringFilterField
  proposalStatusReason: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type PurchaseOrderItemProposed {
  _id: ObjectID!
  quantity: Int!
  quantityFulfilled: Int!
  unitPrice: Int!
  subTotal: Int!
  salesAmount: Int!
  note: String
  mouItem: MouItemForPurchaseOrderItem
  productVariant: ProductVariantForPurchaseOrderItem!
  deliveryDetail: PurchaseOrderItemDelivery
  status: PurchaseOrderItemStatus!
  customerAgreed: Boolean!
  purchaseOrder: PurchaseOrder
  purchaseOrderToSupply: PurchaseOrderToSupply
  purchaseOrderItemReturn: PurchaseOrderItemReturn
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
