input MemberAccessOptionsInput {
    account: AccountAccessInput
    manageOrganizationMember: ManageOrganizationMemberAccessInput
    requestOrganization: RequestOrganizationAccessInput
    viewOrganization: ViewOrganizationAccessInput
}

type MemberAccessOptions {
    account: AccountAccess
    manageOrganizationMember: ManageOrganizationMemberAccess
    requestOrganization: RequestOrganizationAccess
    viewOrganization: ViewOrganizationAccess
}

input CreateMemberAccess {
    access: MemberAccessOptionsInput!
    role: OrganizationMembershipRole!
    organizationType: OrganizationType!
    createdAt: Time
    updatedAt: Time
}

input UpdateMemberAccess {
    _id: ObjectID!
    access: MemberAccessOptionsInput!
    role: OrganizationMembershipRole
    organizationType: OrganizationType
    createdAt: Time
    updatedAt: Time
}

type MemberAccess {
    _id: ObjectID!
    access: MemberAccessOptions!
    role: OrganizationMembershipRole!
    organizationType: OrganizationType!
    createdAt: Time!
    updatedAt: Time!
}