input CreateSupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}

input InternalCreateSupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}

input DatabaseCreateSupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}

input UpdateSupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}

input InternalUpdateSupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}

input DatabaseUpdateSupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}

input SupplyOrderPickUpFilterFields {
  scheduledPickUpTime: TimeFilterField
  actualPickUpTime: TimeFilterField
  note: StringFilterField
}

type SupplyOrderPickUp {
  scheduledPickUpTime: Time
  actualPickUpTime: Time
  note: String
}
