input CreateSupplyOrder {
  items: [CreateSupplyOrderItem]!
  pickUpDetail: CreateSupplyOrderPickUp!
  proposalStatus: EntityProposalStatus
}

input InternalCreateSupplyOrder {
  _id: ObjectID
  publicId: String
  total: Int!
  paidAmount: Int!
  memberAccess: InternalCreateMemberAccess!
  organization: OrganizationForSupplyOrderInput!
  items: [InternalCreateSupplyOrderItem]!
  pickUpDetail: InternalCreateSupplyOrderPickUp!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: InternalUpdateSupplyOrder
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input DatabaseCreateSupplyOrder {
  _id: ObjectID!
  publicId: String!
  total: Int!
  paidAmount: Int!
  organization: OrganizationForSupplyOrderInput!
  items: [ObjectIDOnly]!
  pickUpDetail: DatabaseCreateSupplyOrderPickUp!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateSupplyOrder
  recentLog: ObjectIDOnly
  createdAt: Time!
  updatedAt: Time!
}

input UpdateSupplyOrder {
  _id: ObjectID!
  publicId: String
  total: Int
  paidAmount: Int
  organization: ObjectIDOnly
  items: [UpdateSupplyOrderItem]
  pickUpDetail: UpdateSupplyOrderPickUp
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  """
  Leave the field empty, will be overriden by server.
  """
  submittingAccount: ObjectIDOnly
  """
  Leave the field empty, will be overriden by server.
  """
  recentApprovingAccount: ObjectIDOnly
}

input InternalUpdateSupplyOrder {
  _id: ObjectID!
  publicId: String
  total: Int
  paidAmount: Int
  organization: OrganizationForSupplyOrderInput
  items: [InternalUpdateSupplyOrderItem]
  pickUpDetail: InternalUpdateSupplyOrderPickUp
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: InternalUpdateSupplyOrder
}

input DatabaseUpdateSupplyOrder {
  _id: ObjectID!
  publicId: String
  total: Int
  paidAmount: Int
  organization: OrganizationForSupplyOrderInput
  items: [ObjectIDOnly]
  pickUpDetail: DatabaseUpdateSupplyOrderPickUp
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: DatabaseUpdateSupplyOrder
  updatedAt: Time
}

input SupplyOrderFilterFields {
  _id: ObjectID
  publicId: StringFilterField
  total: IntFilterField
  paidAmount: IntFilterField
  organization: OrganizationForSupplyOrderFilterFields
  items: [ObjectIDOnly]
  pickUpDetail: SupplyOrderPickUpFilterFields
  proposalStatus: StringFilterField
  proposalStatusReason: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: SupplyOrderFilterFields
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type SupplyOrder {
  _id: ObjectID!
  publicId: String
  total: Int!
  paidAmount: Int!
  organization: OrganizationForSupplyOrder!
  items: [SupplyOrderItem]!
  pickUpDetail: SupplyOrderPickUp
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: SupplyOrder
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
