input SupplyOrderProposedInput {
  _id: ObjectID!
  publicId: String
  total: Int
  paidAmount: Int
  totalReturn: Int
  finalSalesAmount: Int
  organization: OrganizationForSupplyOrderInput
  paymentProofPhoto: ObjectIDOnly
  items: [ObjectIDOnly]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input SupplyOrderProposedFilterFields {
  _id: ObjectID
  publicId: StringFilterField
  total: IntFilterField
  paidAmount: IntFilterField
  totalReturn: IntFilterField
  finalSalesAmount: IntFilterField
  organization: OrganizationForSupplyOrderFilterFields
  items: SupplyOrderItemFilterFields
  proposalStatus: StringFilterField
  proposalStatusReason: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type SupplyOrderProposed {
  _id: ObjectID!
  publicId: String
  total: Int!
  paidAmount: Int!
  totalReturn: Int!
  finalSalesAmount: Int!
  organization: OrganizationForSupplyOrder!
  paymentProofPhoto: DescriptivePhoto
  items: [SupplyOrderItem]!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
