input CreateSupplyOrder {
  items: [CreateSupplyOrderItem]!
}

input InternalCreateSupplyOrder {
  items: [InternalCreateSupplyOrderItem]!
  memberAccess: MemberAccessForSupplyOrderInput!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreateSupplyOrder {
  _id: ObjectID!
  publicId: String!
  total: Int!
  totalReturn: Int!
  finalSalesAmount: Int!
  paidAmount: Int!
  organization: OrganizationForSupplyOrderInput!
  items: [ObjectIDOnly]!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateSupplyOrder
  recentLog: ObjectIDOnly
  createdAt: Time!
  updatedAt: Time!
}

input UpdateSupplyOrder {
  _id: ObjectID!
  items: [UpdateSupplyOrderItem]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdateSupplyOrder {
  _id: ObjectID!
  memberAccess: MemberAccessForSupplyOrderInput!
  items: [InternalUpdateSupplyOrderItem]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdateSupplyOrder {
  _id: ObjectID!
  publicId: String
  total: Int
  paidAmount: Int
  totalReturn: Int
  finalSalesAmount: Int
  organization: OrganizationForSupplyOrderInput
  items: [ObjectIDOnly]
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: DatabaseUpdateSupplyOrder
  updatedAt: Time
}

input SupplyOrderFilterFields {
  _id: ObjectID
  publicId: StringFilterField
  total: IntFilterField
  paidAmount: IntFilterField
  totalReturn: IntFilterField
  finalSalesAmount: IntFilterField
  organization: OrganizationForSupplyOrderFilterFields
  items: [ObjectIDOnly]
  proposalStatus: StringFilterField
  proposalStatusReason: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: SupplyOrderFilterFields
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type SupplyOrder {
  _id: ObjectID!
  publicId: String
  total: Int!
  paidAmount: Int!
  totalReturn: Int!
  finalSalesAmount: Int!
  organization: OrganizationForSupplyOrder!
  items: [SupplyOrderItem]!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: SupplyOrder
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
