enum MemberAccessRefType {
    ORGANIZATIONS_BASED
    ACCOUNTS_BASICS
}

input MemberAccessRefOptionsInput {
    account: AccountAccessInput
    manageOrganizationMember: ManageOrganizationMemberAccessInput
    requestOrganization: RequestOrganizationAccessInput
    viewOrganization: ViewOrganizationAccessInput
}

type MemberAccessRefOptions {
    account: AccountAccess
    manageOrganizationMember: ManageOrganizationMemberAccess
    requestOrganization: RequestOrganizationAccess
    viewOrganization: ViewOrganizationAccess
}

input CreateMemberAccessRef {
    access: MemberAccessRefOptionsInput!
    memberAccessRefType: MemberAccessRefType!
    organizationMembershipRole: OrganizationMembershipRole
    organizationType: OrganizationType
    proposalStatus: EntityProposalStatus
    submittingAccount: ObjectIDOnly!
    previousEntity: ObjectIDOnly
    correspondingLog: ObjectIDOnly
    createdAt: Time
    updatedAt: Time
}

input UpdateMemberAccessRef {
    _id: ObjectID!
    access: MemberAccessRefOptionsInput
    memberAccessRefType: MemberAccessRefType
    organizationMembershipRole: OrganizationMembershipRole
    organizationType: OrganizationType
    proposalStatus: EntityProposalStatus
    submittingAccount: ObjectIDOnly!
    approvingAccount: ObjectIDOnly
    updatedAt: Time
}

type MemberAccessRef {
    _id: ObjectID!
    access: MemberAccessRefOptions!
    memberAccessRefType: MemberAccessRefType!
    organizationMembershipRole: OrganizationMembershipRole
    organizationType: OrganizationType
    proposalStatus: EntityProposalStatus!
    submittingAccount: Account!
    approvingAccount: Account
    previousEntity: MemberAccessRef
    correspondingLog: Logging!
    createdAt: Time!
    updatedAt: Time!
}