enum MemberAccessRefType {
  ORGANIZATIONS_BASED
  ACCOUNTS_BASICS
}

input MemberAccessRefOptionsInput {
  accountAccesses: AccountAccessesInput
  addressRegionGroupAccesses: AddressRegionGroupAccessesInput
  manageMemberAccesses: ManageMemberAccessesInput
  organizationAccesses: OrganizationAccessesInput
  memberAccessRefAccesses: MemberAccessRefAccessesInput
  productAccesses: ProductAccessesInput
  tagAccesses: TagAccessesInput
  bulkTaggingAccesses: BulkTaggingAccessesInput
  mouAccesses: MouAccessesInput
  purchaseOrderAccesses: PurchaseOrderAccessesInput
  purchaseOrderItemDeliveryAccesses: PurchaseOrderItemDeliveryAccessesInput
  supplyOrderAccesses: SupplyOrderAccessesInput
  supplyOrderItemPickUpAccesses: SupplyOrderItemPickUpAccessesInput
  invoiceAccesses: InvoiceAccessesInput
  paymentAccesses: PaymentAccessesInput
}

type MemberAccessRefOptions {
  accountAccesses: AccountAccesses
  addressRegionGroupAccesses: AddressRegionGroupAccesses
  manageMemberAccesses: ManageMemberAccesses
  organizationAccesses: OrganizationAccesses
  memberAccessRefAccesses: MemberAccessRefAccesses
  productAccesses: ProductAccesses
  tagAccesses: TagAccesses
  bulkTaggingAccesses: BulkTaggingAccesses
  mouAccesses: MouAccesses
  purchaseOrderAccesses: PurchaseOrderAccesses
  purchaseOrderItemDeliveryAccesses: PurchaseOrderItemDeliveryAccesses
  supplyOrderAccesses: SupplyOrderAccesses
  supplyOrderItemPickUpAccesses: SupplyOrderItemPickUpAccesses
  invoiceAccesses: InvoiceAccesses
  paymentAccesses: PaymentAccesses
}

input CreateMemberAccessRef {
  access: MemberAccessRefOptionsInput!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
}

input InternalCreateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateMemberAccessRef
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdateMemberAccessRef
  recentLog: ObjectIDOnly
  updatedAt: Time
}

input MemberAccessRefFilterFields {
  _id: ObjectID
  access: MemberAccessRefOptionsInput
  memberAccessRefType: StringFilterField
  organizationMembershipRole: StringFilterField
  organizationType: StringFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: MemberAccessRefFilterFields
  recentLog: ObjectIDOnly
}

type MemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptions!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: MemberAccessRef
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
