enum MemberAccessRefType {
  ORGANIZATIONS_BASED
  ACCOUNTS_BASICS
}

input MemberAccessRefOptionsInput {
  accountAccesses: AccountAccessesInput
  manageMemberAccesses: ManageMemberAccessesInput
  organizationAccesses: OrganizationAccessesInput
  memberAccessRefAccesses: MemberAccessRefAccessesInput
  productAccesses: ProductAccessesInput
}

type MemberAccessRefOptions {
  accountAccesses: AccountAccesses
  manageMemberAccesses: ManageMemberAccesses
  organizationAccesses: OrganizationAccesses
  memberAccessRefAccesses: MemberAccessRefAccesses
  productAccesses: ProductAccesses
}

input CreateMemberAccessRef {
  access: MemberAccessRefOptionsInput!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
}

input InternalCreateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: UpdateMemberAccessRef
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  """
  Leave the field empty, will be overriden by server.
  """
  submittingAccount: ObjectIDOnly
  """
  Leave the field empty, will be overriden by server.
  """
  recentApprovingAccount: ObjectIDOnly
}

input InternalUpdateMemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: UpdateMemberAccessRef
  recentLog: ObjectIDOnly
  updatedAt: Time
}

input MemberAccessRefFilterFields {
  _id: ObjectID
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: MemberAccessRefFilterFields
  recentLog: ObjectIDOnly
}

type MemberAccessRef {
  _id: ObjectID!
  access: MemberAccessRefOptions!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus!
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: MemberAccessRef
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
