input MemberAccessRefProposedInput {
  _id: ObjectID!
  access: MemberAccessRefOptionsInput
  memberAccessRefType: MemberAccessRefType
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input MemberAccessRefProposedFilterFields {
  _id: ObjectID
  access: MemberAccessRefOptionsInput
  memberAccessRefType: StringFilterField
  organizationMembershipRole: StringFilterField
  organizationType: StringFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type MemberAccessRefProposed {
  _id: ObjectID!
  access: MemberAccessRefOptions!
  memberAccessRefType: MemberAccessRefType!
  organizationMembershipRole: OrganizationMembershipRole
  organizationType: OrganizationType
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
