input AccountForNotifPayloadInput {
  _id: ObjectID!
  status: AccountStatus!
  statusReason: String
  type: AccountType!
  person: PersonForNotifPayloadInput!
}

type AccountForNotifPayload {
  _id: ObjectID!
  status: AccountStatus!
  statusReason: String
  type: AccountType!
  person: PersonForNotifPayload!
}

input AccountForNotifRecipientInput {
  _id: ObjectID!
  language: Language!
  type: AccountType!
  person: PersonForNotifRecipientInput!
  deviceTokens: [String!]!
}

type AccountForNotifRecipient {
  _id: ObjectID!
  language: Language!
  type: AccountType!
  person: PersonForNotifRecipient!
  deviceTokens: [String!]!
}
