input MemberAccessForNotifPayloadInput {
  _id: ObjectID!
  account: AccountForNotifPayloadInput!
  organization: OrganizationForNotifPayloadInput!
  organizationMembershipRole: OrganizationMembershipRole!
  submittingAccount: AccountForNotifPayloadInput!
}

type MemberAccessForNotifPayload {
  _id: ObjectID!
  account: AccountForNotifPayload!
  organization: OrganizationForNotifPayload!
  organizationMembershipRole: OrganizationMembershipRole!
  submittingAccount: AccountForNotifPayload!
}
