input PersonForNotifPayloadInput {
  _id: ObjectID!
  firstName: String!
  lastName: String!
}

type PersonForNotifPayload {
  _id: ObjectID!
  firstName: String!
  lastName: String!
}

input PersonForNotifRecipientInput {
  _id: ObjectID!
  firstName: String!
  lastName: String!
}

type PersonForNotifRecipient {
  _id: ObjectID!
  firstName: String!
  lastName: String!
}
