input PurchaseOrderForNotifPayloadInput {
  _id: ObjectID!
  publicId: String!
  total: Int
  totalReturn: Int
  finalSalesAmount: Int
  type: PurchaseOrderType
  status: PurchaseOrderStatus
  organization: OrganizationForPurchaseOrderInput
  receivingDateTime: Time
  invoice: InvoiceForPurchaseOrderInput
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  createdAt: Time
  updatedAt: Time
}

type PurchaseOrderForNotifPayload {
  _id: ObjectID!
  publicId: String!
  total: Int!
  finalSalesAmount: Int!
  totalReturn: Int!
  type: PurchaseOrderType!
  status: PurchaseOrderStatus!
  organization: OrganizationForPurchaseOrder!
  receivingDateTime: Time
  invoice: InvoiceForPurchaseOrder
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  createdAt: Time!
  updatedAt: Time!
}
