enum OrganizationMembershipRole {
  STAFF
  MANAGER
  OWNER
}

enum OrganizationMembershipStatus {
  ACTIVE
  INACTIVE
}

input CreateOrganizationMembership {
  person: ObjectIDOnly
  role: OrganizationMembershipRole
  status: OrganizationMembershipStatus
  access: MemberAccessOptionsInput
}

input UpdateOrganizationMembership {
  _id: ObjectID!
  person: ObjectIDOnly
  role: OrganizationMembershipRole
  status: OrganizationMembershipStatus
  access: MemberAccessOptionsInput
}

type OrganizationMembership {
  _id: ObjectID!
  person: Person
  role: OrganizationMembershipRole
  status: OrganizationMembershipStatus
  access: MemberAccessOptions
  defaultAccess: MemberAccess
}
