enum StringOperation {
  IN
  NOT_IN
  CONTAINS
  EQUAL
  NOT_EQUAL
}

enum ObjectIDOperation {
  EQUAL
  NOT_EQUAL
  IN
  NOT_IN
  """
  HAS_VALUES is strictly used for query of field of type **Array**
  and expect `values` field to be filled
  """
  HAS_VALUES
}

enum NumericOperation {
  LESS_THAN
  LESS_THAN_OR_EQUAL
  MORE_THAN
  MORE_THAN_OR_EQUAL
  EQUAL
  NOT_EQUAL
}

enum BooleanOperation {
  EQUAL
  NOT_EQUAL
}

enum TimeOperation {
  LESS_THAN
  LESS_THAN_OR_EQUAL
  MORE_THAN
  MORE_THAN_OR_EQUAL
  EQUAL
  NOT_EQUAL
}
