input StringFilterField {
  operation: StringOperation!
  """
  if value is null, operation should be **EQUAL** or **NOT EQUAL**
  """
  value: String
  values: [String!]
}

input IntFilterField {
  operation: NumericOperation!
  """
  if value is null, operation should be **EQUAL** or **NOT EQUAL**
  """
  value: Int
}

input BooleanFilterField {
  operation: BooleanOperation!
  """
  if value is null, operation should be **EQUAL** or **NOT EQUAL**
  """
  value: Boolean
}

input TimeFilterField {
  operation: TimeOperation!
  """
  if value is null, operation should be **EQUAL** or **NOT EQUAL**
  """
  value: Time
}

input ObjectIDFilterField {
  operation: ObjectIDOperation!
  """
  if value is null, operation should be **EQUAL** or **NOT EQUAL**
  """
  value: ObjectID
  values: [ObjectID]
}
