enum AccountStatus {
  ACTIVE
  INACTIVE
  RECEIVE_ATTENTION
}

enum AccountType {
  PERSON
  SYSTEM_ENTITY
}

input UpdateOtherAccount {
  _id: ID!
  status: AccountStatus
  statusReason: String
  email: String
  type: AccountType
  idCard: NewIDCard
}

input CreateAccount {
  status: AccountStatus
  statusReason: String
  type: AccountType!
  person: ObjectId!
}

input UpdateAccount {
  _id: ID!
  status: AccountStatus
  statusReason: String
  type: AccountType
  person: ObjectId
}

type Account {
  _id: ID!
  status: AccountStatus!
  statusReason: String
  type: AccountType!
  person: Person
}
