input NewAddress {
  latitude: Float
  longitude: Float
  addressNote: String
  phoneNumber: String
}

input UpdateAddress {
  latitude: Float
  longitude: Float
  addressNote: String
  phoneNumber: String
}

type Address {
  resolvedGeocoding: ResolvedGeocoding
  addressNote: String
  phoneNumber: String
}

type ResolvedGeocoding {
  province: String
  district: String
  municipality: String
  zipCode: String
  streetName: String
}
