input MemberAccessForPaymentInput {
  _id: ObjectID!
  organization: OrganizationForMemberAccessInput!
}

type MemberAccessForPayment {
  _id: ObjectID!
  organization: OrganizationForMemberAccess!
}
