input SupplyOrderForPaymentInput {
  _id: ObjectID!
  publicId: String
}

input SupplyOrderForPaymentFilterFields {
  _id: ObjectID
  publicId: StringFilterField
}

type SupplyOrderForPayment {
  _id: ObjectID!
  publicId: String
}
