enum PaymentType {
  CREDIT_PAYMENT_TO_PARTNER
  DEBIT_PAYMENT_FROM_CUSTOMER
}

input CreatePayment {
  amount: Int!
  note: String
  photo: CreateDescriptivePhoto!
  invoice: ObjectIDOnly!
}

input InternalCreatePayment {
  amount: Int!
  note: String
  type: PaymentType
  photo: InternalCreateDescriptivePhoto!
  invoice: ObjectIDOnly
  supplyOrder: ObjectIDOnly
  memberAccess: MemberAccessForPaymentInput!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreatePayment {
  _id: ObjectID!
  amount: Int!
  note: String
  type: PaymentType!
  photo: ObjectIDOnly!
  invoice: InvoiceForPaymentInput
  supplyOrder: SupplyOrderForPaymentInput
  organization: OrganizationForPaymentInput!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: PaymentProposedInput
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdatePayment {
  _id: ObjectID
  amount: Int
  note: String
  photo: UpdateDescriptivePhoto
  invoice: ObjectIDOnly
  supplyOrder: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdatePayment {
  _id: ObjectID
  amount: Int
  note: String
  photo: InternalUpdateDescriptivePhoto
  invoice: ObjectIDOnly
  supplyOrder: ObjectIDOnly
  memberAccess: MemberAccessForPaymentInput
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdatePayment {
  _id: ObjectID!
  amount: Int
  note: String
  type: PaymentType
  photo: ObjectIDOnly
  invoice: InvoiceForPaymentInput
  supplyOrder: SupplyOrderForPaymentInput
  organization: OrganizationForPaymentInput
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: PaymentProposedInput
  recentLog: ObjectIDOnly
  updatedAt: Time
}

input PaymentFilterFields {
  _id: ObjectID
  amount: IntFilterField
  note: StringFilterField
  type: StringFilterField
  invoice: InvoiceForPaymentFilterFields
  supplyOrder: SupplyOrderForPaymentFilterFields
  organization: OrganizationForPaymentFilterFields
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: PaymentProposedFilterFields
  recentLog: ObjectIDOnly
  updatedAt: Time
}

type Payment {
  _id: ObjectID!
  amount: Int!
  note: String
  type: PaymentType!
  photo: DescriptivePhoto!
  invoice: Invoice
  supplyOrder: SupplyOrder
  organization: Organization!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: PaymentProposed
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
