extend type Mutation {
    createSupplyOrder(createSupplyOrder: CreateSupplyOrder!): SupplyOrder!
    updateSupplyOrder(updateSupplyOrder: UpdateSupplyOrder!): SupplyOrder!
}

extend type Query {
    supplyOrders(filterFields: SupplyOrderFilterFields!, paginationOpt: PaginationOptionInput): [SupplyOrder]!
}