enum LoggedActivity {
  CREATE
  UPDATE
  DELETE
}

input CreateLogging {
  collection: String!
  document: ObjectIDOnly!
  oldDocumentJson: String
  newDocumentJson: String
  createdByAccount: ObjectIDOnly!
  activity: LoggedActivity!
  proposalStatus: EntityProposalStatus!
  createdAt: Time
}

input UpdateLogging {
  _id: ObjectID!
  collection: String
  document: ObjectIDOnly
  oldDocumentJson: String
  newDocumentJson: String
  createdByAccount: ObjectIDOnly
  activity: LoggedActivity
  proposalStatus: EntityProposalStatus
  updatedAt: Time
}

input LoggingFilterFields {
  _id: ObjectID
  collection: String
  document: ObjectIDOnly
  createdByAccount: ObjectIDOnly
  activity: LoggedActivity
  proposalStatus: EntityProposalStatus
}

type Logging {
  _id: ObjectID!
  collection: String!
  document: ObjectIDOnlyOutput!
  oldDocumentJson: String
  newDocumentJson: String
  createdByAccount: Account!
  activity: LoggedActivity!
  proposalStatus: EntityProposalStatus!
  createdAt: Time
  updatedAt: Time
}
