enum PurchaseOrderStatus {
  OPEN
  PROCESSED
  CANCELLED
  WAITING_FOR_INVOICE
  INVOICED
  PAID
}

enum PurchaseOrderType {
  MOU_BASED
  RETAIL
}

input CreatePurchaseOrder {
  mouItems: [CreatePurchaseOrderItem]
  retailItems: [CreatePurchaseOrderItem]
}

input InternalCreatePurchaseOrder {
  mouItems: [InternalCreatePurchaseOrderItem]
  retailItems: [InternalCreatePurchaseOrderItem]
  items: [InternalCreatePurchaseOrderItem]
  mou: MouForPurchaseOrderInput!
  type: PurchaseOrderType!
  memberAccess: MemberAccessForPurchaseOrderInput!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreatePurchaseOrder {
  _id: ObjectID!
  publicId: String!
  items: [ObjectIDOnly]
  mou: MouForPurchaseOrderInput!
  total: Int!
  totalReturn: Int!
  finalSalesAmount: Int!
  type: PurchaseOrderType!
  status: PurchaseOrderStatus
  paymentDueDate: Time
  organization: OrganizationForPurchaseOrderInput
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: DatabaseUpdatePurchaseOrder
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdatePurchaseOrder {
  _id: ObjectID!
  items: [UpdatePurchaseOrderItem]
  mou: ObjectIDOnly
  status: PurchaseOrderStatus
  paymentDueDate: Time
  markAsReceived: Boolean
  invoice: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdatePurchaseOrder {
  _id: ObjectID!
  items: [InternalUpdatePurchaseOrderItem]
  mou: MouForPurchaseOrderInput
  type: PurchaseOrderType
  status: PurchaseOrderStatus
  paymentDueDate: Time
  memberAccess: MemberAccessForPurchaseOrderInput!
  markAsReceived: Boolean
  invoice: InvoiceForPurchaseOrderInput
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdatePurchaseOrder {
  _id: ObjectID!
  items: [ObjectIDOnly]
  mou: MouForPurchaseOrderInput
  total: Int
  totalReturn: Int
  finalSalesAmount: Int
  type: PurchaseOrderType
  status: PurchaseOrderStatus
  paymentDueDate: Time
  organization: OrganizationForPurchaseOrderInput
  receivingDateTime: Time
  invoice: InvoiceForPurchaseOrderInput
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: DatabaseUpdatePurchaseOrder
  updatedAt: Time
}

input PurchaseOrderFilterFields {
  _id: ObjectID
  publicId: StringFilterField
  items: [ObjectIDOnly]
  mou: MouFilterFields
  total: IntFilterField
  finalSalesAmount: IntFilterField
  totalReturn: IntFilterField
  type: StringFilterField
  status: StringFilterField
  paymentDueDate: TimeFilterField
  organization: OrganizationFilterFields
  receivingDateTime: TimeFilterField
  invoice: InvoiceForPurchaseOrderFilterFields
  proposalStatus: StringFilterField
  proposalStatusReason: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: PurchaseOrderFilterFields
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type PurchaseOrder {
  _id: ObjectID!
  publicId: String!
  items: [PurchaseOrderItem]
  mou: MouForPurchaseOrder
  total: Int!
  finalSalesAmount: Int!
  totalReturn: Int!
  type: PurchaseOrderType!
  status: PurchaseOrderStatus!
  paymentDueDate: Time
  organization: OrganizationForPurchaseOrder!
  receivingDateTime: Time
  invoice: InvoiceForPurchaseOrder
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: PurchaseOrder
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
