enum Gender {
  MALE
  FEMALE
}

input UpdatePerson {
  _id: ID
  firstName: String
  lastName: String
  gender: Gender
  phoneNumber: String
  email: String
  deviceTokens: [String]
  noOfRecentTransactionToKeep: Int
}

input CreatePerson {
  firstName: String!
  lastName: String!
  gender: Gender
  phoneNumber: String!
  email: String!
  deviceTokens: [String]
  noOfRecentTransactionToKeep: Int
  createdAt: String
}

interface iPerson {
  _id: ID!
  firstName: String!
  lastName: String!
  gender: Gender!
  phoneNumber: String
  email: String!
  idCard: IDCard
  noOfRecentTransactionToKeep: Int!
  organizationMembership: OrganizationMember
  createdAt: String!
}

type Person implements iPerson {
  _id: ID!
  firstName: String!
  lastName: String!
  gender: Gender!
  phoneNumber: String
  email: String!
  idCard: IDCard
  noOfRecentTransactionToKeep: Int!
  organizationMembership: OrganizationMember
  createdAt: String!
}

type PersonDetailed implements iPerson {
  _id: ID!
  firstName: String!
  lastName: String!
  gender: Gender!
  phoneNumber: String
  email: String!
  idCard: IDCard
  noOfRecentTransactionToKeep: Int!
  organizationMembership: OrganizationMember
  deviceTokens: [String]!
  createdAt: String!
}
