input AccountForPurchaseOrderItemInput {
  _id: ObjectID!
  email: String
  language: Language
  type: AccountType
  person: PersonForPurchaseOrderItemInput
}

input AccountForPurchaseOrderItemFilterFields {
  _id: ObjectID
  email: StringFilterField
}

type AccountForPurchaseOrderItem {
  _id: ObjectID!
  email: String
  language: Language
  type: AccountType
  person: PersonForPurchaseOrderItem
}
