input MouItemForPurchaseOrderItemInput {
  _id: ObjectID!
  agreedProduct: InternalAgreedProductInput!
  mou: ObjectIDOnly!
}

type MouItemForPurchaseOrderItem {
  _id: ObjectID!
  agreedProduct: AgreedProduct!
  mou: ObjectIDOnlyOutput!
}
