input MemberAccessForSupplyOrderInput {
  _id: ObjectID!
  organization: OrganizationForMemberAccessInput!
}

type MemberAccessForSupplyOrder {
  _id: ObjectID!
  organization: OrganizationForMemberAccess!
}
