input MouItemProposedInput {
  _id: ObjectID!
  product: ObjectIDOnly
  agreedProduct: InternalAgreedProductInput
  isActive: Boolean
  mou: ObjectIDOnly
  organization: OrganizationForMouItemInput
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input MouItemProposedFilterFields {
  _id: ObjectID
  product: ObjectIDOnlyFilterField
  agreedProduct: AgreedProductFilterFields
  isActive: Boolean
  mou: ObjectIDOnlyFilterField
  organization: OrganizationForMouItemFilterFields
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type MouItemProposed {
  _id: ObjectID!
  product: Product!
  agreedProduct: AgreedProduct
  isActive: Boolean!
  mou: Mou!
  organization: OrganizationForMouItem!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
