input CreateMouItem {
  product: ObjectIDOnly!
  agreedProduct: AgreedProductInput
  isActive: Boolean
}

input InternalCreateMouItem {
  _id: ObjectID
  product: ObjectIDOnly!
  agreedProduct: AgreedProductInput
  isActive: Boolean
  mou: ObjectIDOnly!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseCreateMouItem {
  _id: ObjectID!
  product: ObjectIDOnly!
  agreedProduct: InternalAgreedProductInput
  isActive: Boolean
  mou: ObjectIDOnly!
  proposalStatus: EntityProposalStatus
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  proposedChanges: MouItemProposedInput
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input UpdateMouItem {
  """
  Note: ID is optional in here. (a) If present, an update will occur when submitting the request.
  (b) If not present, the request will create new object.
  """
  _id: ObjectID
  product: ObjectIDOnly
  agreedProduct: AgreedProductInput
  isActive: Boolean
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
}

input InternalUpdateMouItem {
  _id: ObjectID
  product: ObjectIDOnly
  agreedProduct: AgreedProductInput
  isActive: Boolean
  mou: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
}

input DatabaseUpdateMouItem {
  _id: ObjectID!
  product: ObjectIDOnly
  agreedProduct: InternalAgreedProductInput
  isActive: Boolean
  mou: ObjectIDOnly
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: MouItemProposedInput
  updatedAt: Time
}

input MouItemFilterFields {
  _id: ObjectID
  product: ObjectIDOnlyFilterField
  agreedProduct: AgreedProductFilterFields
  isActive: Boolean
  mou: ObjectIDOnlyFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  proposedChanges: MouItemProposedFilterFields
}

type MouItem {
  _id: ObjectID!
  product: Product!
  agreedProduct: AgreedProduct
  isActive: Boolean!
  mou: Mou!
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account!
  recentApprovingAccount: Account
  proposedChanges: MouItemProposed
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
