input TaggingProposedInput {
  _id: ObjectID!
  tag: TagForTaggingInput
  correlatedTag: ObjectIDOnly
  product: ObjectIDOnly
  organization: ObjectIDOnly
  isActive: Boolean
  taggingType: TaggingType
  proposalStatus: EntityProposalStatus
  proposalStatusReason: String
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: Time
  updatedAt: Time
}

input TaggingProposedFilterFields {
  _id: ObjectID
  tag: TagForTaggingFilterFields
  correlatedTag: ObjectIDOnly
  product: ObjectIDOnly
  organization: ObjectIDOnly
  isActive: BooleanFilterField
  taggingType: StringFilterField
  proposalStatus: StringFilterField
  submittingAccount: ObjectIDOnly
  recentApprovingAccount: ObjectIDOnly
  recentLog: ObjectIDOnly
  createdAt: TimeFilterField
  updatedAt: TimeFilterField
}

type TaggingProposed {
  _id: ObjectID!
  tag: Tag!
  correlatedTag: Tag
  product: Product
  organization: Organization
  isActive: Boolean!
  taggingType: TaggingType
  proposalStatus: EntityProposalStatus!
  proposalStatusReason: String
  submittingAccount: Account
  recentApprovingAccount: Account
  recentLog: Logging!
  createdAt: Time!
  updatedAt: Time!
}
