scalar Upload
scalar Time

scalar ObjectID

input ObjectIDOnly {
  _id: ObjectID
}

input ObjectIDOnlyFilterField {
  _id: ObjectIDFilterField
}

type ObjectIDOnlyOutput {
  _id: ObjectID
}

input PaginationOptionInput {
  lastObjectID: ObjectID
  queryLimit: Int
}
