input PurchaseOrderToSupplyForSupplyOrderItemInput {
  _id: ObjectID!
  quantityRequested: Int!
  productVariant: ProductVariantForSupplyOrderItemInput!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  addressRegionGroup: AddressRegionGroupForSupplyOrderItemInput!
  createdAt: Time!
  updatedAt: Time!
}

input PurchaseOrderToSupplyForSupplyOrderItemFilterFields {
  _id: ObjectID
  quantityRequested: IntFilterField
  productVariant: ProductVariantForSupplyOrderItemFilterFields
  timeSlot: StringFilterField
  expectedArrivalDate: TimeFilterField
  addressRegionGroup: AddressRegionGroupForSupplyOrderItemFilterFields
}

type PurchaseOrderToSupplyForSupplyOrderItem {
  _id: ObjectID!
  quantityRequested: Int!
  productVariant: ProductVariantForSupplyOrderItem!
  timeSlot: DeliveryTimeSlot!
  expectedArrivalDate: Time!
  addressRegionGroup: AddressRegionGroupForSupplyOrderItem!
  createdAt: Time!
  updatedAt: Time!
}
